services:
  - type: web
    name: descall
    runtime: node
    buildCommand: cd frontend && npm install && npm run build && cd backend && npm install
    startCommand: cd frontend/backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
      - key: ALLOW_ALL_ORIGINS
        value: "true"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_API_BASE_URL
        value: "https://descall-qzkg.onrender.com"
