/**
 * Extended Applications Database — 500+ NEW desktop PC apps with unique emojis
 * Merged into PROCESS_DB via spread operator.
 */

export const EXTRA_APPS = {
  // ─── CLOUD STORAGE & FILE SYNC (~50) ─────────────────────────────────────
  'dropbox.exe':                        { name: 'Dropbox',             type: 'app', category: 'cloud-storage', icon: '📦' },
  'googledrivesync.exe':                { name: 'Google Drive',        type: 'app', category: 'cloud-storage', icon: '📁' },
  'googledrive.exe':                    { name: 'Google Drive',        type: 'app', category: 'cloud-storage', icon: '📁' },
  'googlebackupandsync.exe':            { name: 'Google Backup & Sync',type: 'app', category: 'cloud-storage', icon: '🔄' },
  'onedrive.exe':                       { name: 'OneDrive',            type: 'app', category: 'cloud-storage', icon: '☁️' },
  'skydrive.exe':                       { name: 'SkyDrive',            type: 'app', category: 'cloud-storage', icon: '☁️' },
  'icloud.exe':                         { name: 'iCloud',              type: 'app', category: 'cloud-storage', icon: '🍎' },
  'icloudservices.exe':                 { name: 'iCloud Services',     type: 'app', category: 'cloud-storage', icon: '🍎' },
  'pcloud.exe':                         { name: 'pCloud',              type: 'app', category: 'cloud-storage', icon: '💾' },
  'megasync.exe':                       { name: 'Mega',                type: 'app', category: 'cloud-storage', icon: '🐘' },
  'mega.exe':                           { name: 'Mega',                type: 'app', category: 'cloud-storage', icon: '🐘' },
  'box.exe':                            { name: 'Box',                 type: 'app', category: 'cloud-storage', icon: '📦' },
  'boxdrive.exe':                       { name: 'Box Drive',           type: 'app', category: 'cloud-storage', icon: '📦' },
  'boxsync.exe':                        { name: 'Box Sync',            type: 'app', category: 'cloud-storage', icon: '📦' },
  'nextcloud.exe':                      { name: 'Nextcloud',           type: 'app', category: 'cloud-storage', icon: '🌩️' },
  'owncloud.exe':                       { name: 'ownCloud',            type: 'app', category: 'cloud-storage', icon: '☁️' },
  'syncthing.exe':                      { name: 'Syncthing',           type: 'app', category: 'cloud-storage', icon: '🔄' },
  'resilio-sync.exe':                   { name: 'Resilio Sync',        type: 'app', category: 'cloud-storage', icon: '⚡' },
  'btsync.exe':                         { name: 'BitTorrent Sync',     type: 'app', category: 'cloud-storage', icon: '⚡' },
  'yandexdisk.exe':                     { name: 'Yandex Disk',         type: 'app', category: 'cloud-storage', icon: '🇷🇺' },
  'disk.yandex.exe':                    { name: 'Yandex Disk',         type: 'app', category: 'cloud-storage', icon: '🇷🇺' },
  'tresorit.exe':                       { name: 'Tresorit',            type: 'app', category: 'cloud-storage', icon: '🔐' },
  'syncplicity.exe':                    { name: 'Syncplicity',         type: 'app', category: 'cloud-storage', icon: '🔗' },
  'sugarsync.exe':                      { name: 'SugarSync',           type: 'app', category: 'cloud-storage', icon: '🍬' },
  'backblaze.exe':                      { name: 'Backblaze',           type: 'app', category: 'cloud-storage', icon: '🔥' },
  'backblazedrive.exe':                 { name: 'Backblaze Drive',     type: 'app', category: 'cloud-storage', icon: '🔥' },
  'spideroak.exe':                      { name: 'SpiderOak',           type: 'app', category: 'cloud-storage', icon: '🕷️' },
  'idrive.exe':                         { name: 'IDrive',              type: 'app', category: 'cloud-storage', icon: '💿' },
  'crashplan.exe':                      { name: 'CrashPlan',           type: 'app', category: 'cloud-storage', icon: '💥' },
  'seafile.exe':                        { name: 'Seafile',             type: 'app', category: 'cloud-storage', icon: '🌊' },
  'jottacloud.exe':                     { name: 'Jottacloud',          type: 'app', category: 'cloud-storage', icon: '📝' },
  'icedrive.exe':                       { name: 'Icedrive',            type: 'app', category: 'cloud-storage', icon: '🧊' },
  'kdrive.exe':                         { name: 'kDrive',              type: 'app', category: 'cloud-storage', icon: '🇨🇭' },
  'filen.exe':                          { name: 'Filen',               type: 'app', category: 'cloud-storage', icon: '📂' },
  'sync.exe':                           { name: 'Sync.com',            type: 'app', category: 'cloud-storage', icon: '♻️' },
  'workdocs.exe':                       { name: 'Amazon WorkDocs',     type: 'app', category: 'cloud-storage', icon: '📋' },
  'amazonclouddrive.exe':               { name: 'Amazon Cloud Drive',  type: 'app', category: 'cloud-storage', icon: '📦' },
  'acd.exe':                            { name: 'Amazon Cloud Drive',  type: 'app', category: 'cloud-storage', icon: '📦' },
  'degoo.exe':                          { name: 'Degoo',               type: 'app', category: 'cloud-storage', icon: '📀' },
  'livedrive.exe':                      { name: 'Livedrive',           type: 'app', category: 'cloud-storage', icon: '💿' },
  'carbonite.exe':                      { name: 'Carbonite',           type: 'app', category: 'cloud-storage', icon: '💎' },
  'opendrive.exe':                      { name: 'OpenDrive',           type: 'app', category: 'cloud-storage', icon: '🔓' },
  'cubby.exe':                          { name: 'Cubby',               type: 'app', category: 'cloud-storage', icon: '📦' },
  'mozy.exe':                           { name: 'Mozy',                type: 'app', category: 'cloud-storage', icon: '💾' },
  'zoolz.exe':                          { name: 'Zoolz',               type: 'app', category: 'cloud-storage', icon: '🐘' },
  'nordlocker.exe':                     { name: 'NordLocker',          type: 'app', category: 'cloud-storage', icon: '🔒' },
  'internxt.exe':                       { name: 'Internxt',            type: 'app', category: 'cloud-storage', icon: '🌍' },
  'skiff.exe':                          { name: 'Skiff Drive',         type: 'app', category: 'cloud-storage', icon: '⛵' },
  'stashfolder.exe':                    { name: 'Stash',               type: 'app', category: 'cloud-storage', icon: '📦' },
  'koofr.exe':                          { name: 'Koofr',               type: 'app', category: 'cloud-storage', icon: '🐨' },
  'mailrucloud.exe':                    { name: 'Mail.ru Cloud',       type: 'app', category: 'cloud-storage', icon: '📬' },

  // ─── SECURITY, VPN & ANTIVIRUS (~50) ─────────────────────────────────────
  'nordvpn.exe':                        { name: 'NordVPN',             type: 'app', category: 'security', icon: '🧭' },
  'expressvpn.exe':                     { name: 'ExpressVPN',          type: 'app', category: 'security', icon: '🚀' },
  'protonvpn.exe':                      { name: 'Proton VPN',          type: 'app', category: 'security', icon: '⚛️' },
  'mullvad.exe':                        { name: 'Mullvad VPN',         type: 'app', category: 'security', icon: '🐭' },
  'mullvadvpn.exe':                     { name: 'Mullvad VPN',         type: 'app', category: 'security', icon: '🐭' },
  'surfshark.exe':                      { name: 'Surfshark',           type: 'app', category: 'security', icon: '🦈' },
  'cyberghost.exe':                     { name: 'CyberGhost VPN',      type: 'app', category: 'security', icon: '👻' },
  'privateinternetaccess.exe':          { name: 'PIA VPN',             type: 'app', category: 'security', icon: '🔐' },
  'pia.exe':                            { name: 'PIA VPN',             type: 'app', category: 'security', icon: '🔐' },
  'ipvanish.exe':                       { name: 'IPVanish',            type: 'app', category: 'security', icon: '🛡️' },
  'hotspotshield.exe':                  { name: 'Hotspot Shield',      type: 'app', category: 'security', icon: '🛡️' },
  'tunnelbear.exe':                     { name: 'TunnelBear',          type: 'app', category: 'security', icon: '🐻' },
  'windscribe.exe':                     { name: 'Windscribe',          type: 'app', category: 'security', icon: '💨' },
  'hidemevpn.exe':                      { name: 'Hide.me VPN',         type: 'app', category: 'security', icon: '🙈' },
  'vyprvpn.exe':                        { name: 'VyprVPN',             type: 'app', category: 'security', icon: '🐍' },
  'purevpn.exe':                        { name: 'PureVPN',             type: 'app', category: 'security', icon: '💎' },
  'strongvpn.exe':                      { name: 'StrongVPN',           type: 'app', category: 'security', icon: '💪' },
  'avast.exe':                          { name: 'Avast',               type: 'app', category: 'security', icon: '🔰' },
  'avastui.exe':                        { name: 'Avast',               type: 'app', category: 'security', icon: '🔰' },
  'avg.exe':                            { name: 'AVG',                 type: 'app', category: 'security', icon: '🛡️' },
  'avgantivirus.exe':                   { name: 'AVG Antivirus',       type: 'app', category: 'security', icon: '🛡️' },
  'avira.exe':                          { name: 'Avira',               type: 'app', category: 'security', icon: '🛡️' },
  'kaspersky.exe':                      { name: 'Kaspersky',           type: 'app', category: 'security', icon: '🔒' },
  'ksde.exe':                           { name: 'Kaspersky',           type: 'app', category: 'security', icon: '🔒' },
  'bitdefender.exe':                    { name: 'Bitdefender',         type: 'app', category: 'security', icon: '🛡️' },
  'bdagent.exe':                        { name: 'Bitdefender',         type: 'app', category: 'security', icon: '🛡️' },
  'eset.exe':                           { name: 'ESET',                type: 'app', category: 'security', icon: '🛡️' },
  'egui.exe':                           { name: 'ESET',                type: 'app', category: 'security', icon: '🛡️' },
  'mcshield.exe':                       { name: 'McAfee',              type: 'app', category: 'security', icon: '🛡️' },
  'mcapexe.exe':                        { name: 'McAfee',              type: 'app', category: 'security', icon: '🛡️' },
  'norton.exe':                         { name: 'Norton',              type: 'app', category: 'security', icon: '🔰' },
  'ns.exe':                             { name: 'Norton',              type: 'app', category: 'security', icon: '🔰' },
  'ccsvchst.exe':                       { name: 'Norton',              type: 'app', category: 'security', icon: '🔰' },
  'sophos.exe':                         { name: 'Sophos',              type: 'app', category: 'security', icon: '🔒' },
  'sophosui.exe':                       { name: 'Sophos',              type: 'app', category: 'security', icon: '🔒' },
  'f-secure.exe':                       { name: 'F-Secure',            type: 'app', category: 'security', icon: '🔐' },
  'fshoster32.exe':                     { name: 'F-Secure',            type: 'app', category: 'security', icon: '🔐' },
  'pandasecurity.exe':                  { name: 'Panda Security',      type: 'app', category: 'security', icon: '🐼' },
  'psanhost.exe':                       { name: 'Panda Security',      type: 'app', category: 'security', icon: '🐼' },
  'zonealarm.exe':                      { name: 'ZoneAlarm',           type: 'app', category: 'security', icon: '🔥' },
  'glasswire.exe':                      { name: 'GlassWire',           type: 'app', category: 'security', icon: '🔮' },
  'glasswireui.exe':                    { name: 'GlassWire',           type: 'app', category: 'security', icon: '🔮' },
  'protonvpn-service.exe':              { name: 'Proton VPN',          type: 'app', category: 'security', icon: '⚛️' },
  'openvpn.exe':                        { name: 'OpenVPN',             type: 'app', category: 'security', icon: '🔓' },
  'wireguard.exe':                      { name: 'WireGuard',           type: 'app', category: 'security', icon: '⚡' },
  'wg.exe':                             { name: 'WireGuard',           type: 'app', category: 'security', icon: '⚡' },
  'outline-client.exe':                 { name: 'Outline VPN',         type: 'app', category: 'security', icon: '📋' },
  'outline.exe':                        { name: 'Outline VPN',         type: 'app', category: 'security', icon: '📋' },

  // ─── SYSTEM UTILITIES & MONITORING (~50) ───────────────────────────────────
  'ccleaner.exe':                       { name: 'CCleaner',            type: 'app', category: 'system', icon: '🧹' },
  'ccleaner64.exe':                     { name: 'CCleaner',            type: 'app', category: 'system', icon: '🧹' },
  'revo_uninstaller.exe':               { name: 'Revo Uninstaller',    type: 'app', category: 'system', icon: '🗑️' },
  'revouninstaller.exe':                { name: 'Revo Uninstaller',    type: 'app', category: 'system', icon: '🗑️' },
  'revo.exe':                           { name: 'Revo Uninstaller',    type: 'app', category: 'system', icon: '🗑️' },
  'processhacker.exe':                  { name: 'Process Hacker',      type: 'app', category: 'system', icon: '🔍' },
  'processhacker2.exe':                 { name: 'Process Hacker 2',    type: 'app', category: 'system', icon: '🔍' },
  'procexp.exe':                        { name: 'Process Explorer',    type: 'app', category: 'system', icon: '🔍' },
  'procexp64.exe':                      { name: 'Process Explorer',    type: 'app', category: 'system', icon: '🔍' },
  'hwmonitor.exe':                      { name: 'HWMonitor',           type: 'app', category: 'system', icon: '🌡️' },
  'cpuid-hwmonitor.exe':                { name: 'HWMonitor',           type: 'app', category: 'system', icon: '🌡️' },
  'speedfan.exe':                       { name: 'SpeedFan',            type: 'app', category: 'system', icon: '💨' },
  'crystaldiskinfo.exe':                { name: 'CrystalDiskInfo',     type: 'app', category: 'system', icon: '💿' },
  'cdi.exe':                            { name: 'CrystalDiskInfo',     type: 'app', category: 'system', icon: '💿' },
  'aida64.exe':                         { name: 'AIDA64',              type: 'app', category: 'system', icon: '🔬' },
  'aida64business.exe':                 { name: 'AIDA64 Business',     type: 'app', category: 'system', icon: '🔬' },
  'msikombustor.exe':                   { name: 'MSI Kombustor',       type: 'app', category: 'system', icon: '🔥' },
  'furmark.exe':                        { name: 'FurMark',             type: 'app', category: 'system', icon: '🐰' },
  'geeks3dfurmark.exe':                 { name: 'FurMark',             type: 'app', category: 'system', icon: '🐰' },
  '3dmark.exe':                         { name: '3DMark',              type: 'app', category: 'system', icon: '📊' },
  'cinebench.exe':                      { name: 'Cinebench',           type: 'app', category: 'system', icon: '🎬' },
  'cinebenchr23.exe':                   { name: 'Cinebench R23',       type: 'app', category: 'system', icon: '🎬' },
  'crystaldiskmark.exe':                { name: 'CrystalDiskMark',     type: 'app', category: 'system', icon: '💿' },
  'cdm.exe':                            { name: 'CrystalDiskMark',     type: 'app', category: 'system', icon: '💿' },
  'userbenchmark.exe':                  { name: 'UserBenchmark',     type: 'app', category: 'system', icon: '📈' },
  'occt.exe':                           { name: 'OCCT',                type: 'app', category: 'system', icon: '🔬' },
  'throttlestop.exe':                   { name: 'ThrottleStop',        type: 'app', category: 'system', icon: '🛑' },
  'xtu.exe':                            { name: 'Intel XTU',           type: 'app', category: 'system', icon: '⚡' },
  'intelxtu.exe':                       { name: 'Intel XTU',           type: 'app', category: 'system', icon: '⚡' },
  'ryzenmaster.exe':                    { name: 'Ryzen Master',        type: 'app', category: 'system', icon: '🔧' },
  'amdryzenmaster.exe':                 { name: 'Ryzen Master',        type: 'app', category: 'system', icon: '🔧' },
  'afterburner.exe':                    { name: 'MSI Afterburner',     type: 'app', category: 'system', icon: '🔥' },
  'rivatuner.exe':                      { name: 'RivaTuner',           type: 'app', category: 'system', icon: '📊' },
  'rtss.exe':                           { name: 'RivaTuner Statistics',type: 'app', category: 'system', icon: '📊' },
  'nzxtcam.exe':                        { name: 'NZXT CAM',            type: 'app', category: 'system', icon: '📷' },
  'corsairicue.exe':                    { name: 'Corsair iCUE',        type: 'app', category: 'system', icon: '💡' },
  'icue.exe':                           { name: 'Corsair iCUE',        type: 'app', category: 'system', icon: '💡' },
  'signalrgb.exe':                      { name: 'SignalRGB',           type: 'app', category: 'system', icon: '🌈' },
  'openrgb.exe':                        { name: 'OpenRGB',             type: 'app', category: 'system', icon: '🌈' },
  'hwinfo.exe':                         { name: 'HWiNFO',              type: 'app', category: 'system', icon: '📊' },
  'hwinfo64.exe':                       { name: 'HWiNFO64',            type: 'app', category: 'system', icon: '📊' },
  'hwinfo32.exe':                       { name: 'HWiNFO32',            type: 'app', category: 'system', icon: '📊' },
  'cpu-z.exe':                          { name: 'CPU-Z',               type: 'app', category: 'system', icon: '🔬' },
  'cpuz.exe':                           { name: 'CPU-Z',               type: 'app', category: 'system', icon: '🔬' },
  'gpu-z.exe':                          { name: 'GPU-Z',               type: 'app', category: 'system', icon: '🔬' },
  'gpuz.exe':                           { name: 'GPU-Z',               type: 'app', category: 'system', icon: '🔬' },
  'speccy.exe':                         { name: 'Speccy',              type: 'app', category: 'system', icon: '🔍' },
  'speccy64.exe':                       { name: 'Speccy',              type: 'app', category: 'system', icon: '🔍' },
  'autoruns.exe':                       { name: 'Autoruns',            type: 'app', category: 'system', icon: '⚙️' },
  'autorunsc.exe':                      { name: 'Autoruns',            type: 'app', category: 'system', icon: '⚙️' },

  // ─── REMOTE DESKTOP & ACCESS (~25) ─────────────────────────────────────────
  'teamviewer.exe':                     { name: 'TeamViewer',          type: 'app', category: 'remote', icon: '🖥️' },
  'teamviewer_service.exe':             { name: 'TeamViewer',          type: 'app', category: 'remote', icon: '🖥️' },
  'anydesk.exe':                        { name: 'AnyDesk',             type: 'app', category: 'remote', icon: '🖥️' },
  'chromeremotedesktop.exe':            { name: 'Chrome Remote Desktop',type: 'app', category: 'remote', icon: '🖥️' },
  'remoting_host.exe':                  { name: 'Chrome Remote Desktop',type: 'app', category: 'remote', icon: '🖥️' },
  'splashtop.exe':                      { name: 'Splashtop',           type: 'app', category: 'remote', icon: '💦' },
  'strwinclt.exe':                      { name: 'Splashtop',           type: 'app', category: 'remote', icon: '💦' },
  'rustdesk.exe':                       { name: 'RustDesk',            type: 'app', category: 'remote', icon: '🔧' },
  'tightvnc.exe':                       { name: 'TightVNC',            type: 'app', category: 'remote', icon: '🖥️' },
  'tvnserver.exe':                      { name: 'TightVNC Server',     type: 'app', category: 'remote', icon: '🖥️' },
  'uvnc_service.exe':                   { name: 'UltraVNC',            type: 'app', category: 'remote', icon: '🖥️' },
  'vncviewer.exe':                      { name: 'VNC Viewer',            type: 'app', category: 'remote', icon: '🖥️' },
  'vncserver.exe':                      { name: 'VNC Server',            type: 'app', category: 'remote', icon: '🖥️' },
  'realvnc.exe':                        { name: 'RealVNC',             type: 'app', category: 'remote', icon: '🖥️' },
  'remotedesktopmanager.exe':           { name: 'Remote Desktop Manager',type: 'app', category: 'remote', icon: '🖥️' },
  'rdm.exe':                            { name: 'Remote Desktop Manager',type: 'app', category: 'remote', icon: '🖥️' },
  'mremoteng.exe':                      { name: 'mRemoteNG',           type: 'app', category: 'remote', icon: '🖥️' },
  'royalts.exe':                        { name: 'Royal TS',            type: 'app', category: 'remote', icon: '👑' },
  'dameware.exe':                       { name: 'DameWare',            type: 'app', category: 'remote', icon: '🖥️' },
  'gotoassist.exe':                     { name: 'GoToAssist',          type: 'app', category: 'remote', icon: '🖥️' },
  'gotomeeting.exe':                    { name: 'GoToMeeting',         type: 'app', category: 'remote', icon: '🖥️' },
  'g2m.exe':                            { name: 'GoToMeeting',         type: 'app', category: 'remote', icon: '🖥️' },
  'logmein.exe':                        { name: 'LogMeIn',             type: 'app', category: 'remote', icon: '🖥️' },
  'connectwise.exe':                    { name: 'ConnectWise',         type: 'app', category: 'remote', icon: '🔗' },
  'screenconnect.exe':                  { name: 'ScreenConnect',       type: 'app', category: 'remote', icon: '🖥️' },

  // ─── TORRENT & P2P (~20) ───────────────────────────────────────────────────
  'qbittorrent.exe':                    { name: 'qBittorrent',         type: 'app', category: 'torrent', icon: '🌊' },
  'utorrent.exe':                       { name: 'uTorrent',            type: 'app', category: 'torrent', icon: '📥' },
  'bittorrent.exe':                     { name: 'BitTorrent',          type: 'app', category: 'torrent', icon: '📥' },
  'transmission-qt.exe':                { name: 'Transmission',        type: 'app', category: 'torrent', icon: '📡' },
  'transmission.exe':                   { name: 'Transmission',        type: 'app', category: 'torrent', icon: '📡' },
  'deluge.exe':                         { name: 'Deluge',              type: 'app', category: 'torrent', icon: '🌊' },
  'tixati.exe':                         { name: 'Tixati',              type: 'app', category: 'torrent', icon: '📥' },
  'picotorrent.exe':                    { name: 'PicoTorrent',         type: 'app', category: 'torrent', icon: '📥' },
  'frostwire.exe':                      { name: 'FrostWire',           type: 'app', category: 'torrent', icon: '❄️' },
  'vuze.exe':                           { name: 'Vuze',                type: 'app', category: 'torrent', icon: '🦋' },
  'azureus.exe':                        { name: 'Vuze',                type: 'app', category: 'torrent', icon: '🦋' },
  'emule.exe':                          { name: 'eMule',               type: 'app', category: 'torrent', icon: '🐴' },
  'edonkey2000.exe':                    { name: 'eDonkey',             type: 'app', category: 'torrent', icon: '🐴' },
  'shareaza.exe':                       { name: 'Shareaza',            type: 'app', category: 'torrent', icon: '🔗' },
  'ares.exe':                           { name: 'Ares Galaxy',         type: 'app', category: 'torrent', icon: '🌌' },
  'mediaget.exe':                       { name: 'MediaGet',            type: 'app', category: 'torrent', icon: '📥' },
  'zamunda.exe':                        { name: 'Zamunda',             type: 'app', category: 'torrent', icon: '🇧🇬' },
  'halite.exe':                         { name: 'Halite',              type: 'app', category: 'torrent', icon: '💎' },
  'hadouken.exe':                       { name: 'Hadouken',            type: 'app', category: 'torrent', icon: '👊' },
  'biglybt.exe':                        { name: 'BiglyBT',             type: 'app', category: 'torrent', icon: '🐝' },

  // ─── SOCIAL MEDIA DESKTOP (~30) ────────────────────────────────────────────
  'facebookmessenger.exe':              { name: 'Facebook Messenger',  type: 'app', category: 'social', icon: '💬' },
  'messenger.exe':                      { name: 'Messenger',           type: 'app', category: 'social', icon: '💬' },
  'instagram.exe':                      { name: 'Instagram',           type: 'app', category: 'social', icon: '📸' },
  'tiktok.exe':                         { name: 'TikTok',              type: 'app', category: 'social', icon: '🎵' },
  'snapchat.exe':                       { name: 'Snapchat',            type: 'app', category: 'social', icon: '👻' },
  'twitter.exe':                        { name: 'X (Twitter)',         type: 'app', category: 'social', icon: '🐦' },
  'x.exe':                              { name: 'X (Twitter)',         type: 'app', category: 'social', icon: '❌' },
  'tweetdeck.exe':                      { name: 'TweetDeck',           type: 'app', category: 'social', icon: '🐦' },
  'reddit.exe':                         { name: 'Reddit',              type: 'app', category: 'social', icon: '🔴' },
  'pinterest.exe':                      { name: 'Pinterest',           type: 'app', category: 'social', icon: '📌' },
  'linkedin.exe':                       { name: 'LinkedIn',            type: 'app', category: 'social', icon: '💼' },
  'tumblr.exe':                         { name: 'Tumblr',              type: 'app', category: 'social', icon: '📝' },
  'mastodon.exe':                       { name: 'Mastodon',            type: 'app', category: 'social', icon: '🐘' },
  'discordptb.exe':                     { name: 'Discord PTB',         type: 'app', category: 'social', icon: '💬' },
  'discordcanary.exe':                  { name: 'Discord Canary',      type: 'app', category: 'social', icon: '💬' },
  'telegramdesktop.exe':                { name: 'Telegram Desktop',    type: 'app', category: 'social', icon: '✈️' },
  'whatsapp.exe':                       { name: 'WhatsApp',            type: 'app', category: 'social', icon: '💬' },
  'signal.exe':                         { name: 'Signal',              type: 'app', category: 'social', icon: '🔐' },
  'viber.exe':                          { name: 'Viber',               type: 'app', category: 'social', icon: '📞' },
  'line.exe':                           { name: 'LINE',                type: 'app', category: 'social', icon: '📱' },
  'wechat.exe':                         { name: 'WeChat',              type: 'app', category: 'social', icon: '💬' },
  'wechatapp.exe':                      { name: 'WeChat',              type: 'app', category: 'social', icon: '💬' },
  'qq.exe':                             { name: 'QQ',                  type: 'app', category: 'social', icon: '🐧' },
  'tim.exe':                            { name: 'TIM',                 type: 'app', category: 'social', icon: '💬' },
  'skype.exe':                          { name: 'Skype',               type: 'app', category: 'social', icon: '📞' },
  'skypeapp.exe':                       { name: 'Skype',               type: 'app', category: 'social', icon: '📞' },
  'threema.exe':                        { name: 'Threema',             type: 'app', category: 'social', icon: '🔒' },
  'wire.exe':                           { name: 'Wire',                type: 'app', category: 'social', icon: '⚡' },
  'icq.exe':                            { name: 'ICQ',                 type: 'app', category: 'social', icon: '🌸' },
  'trillian.exe':                       { name: 'Trillian',            type: 'app', category: 'social', icon: '🦋' },

  // ─── FINANCE, TRADING & CRYPTO DESKTOP (~30) ───────────────────────────────
  'binance.exe':                        { name: 'Binance',             type: 'app', category: 'finance', icon: '💰' },
  'coinbase.exe':                       { name: 'Coinbase',            type: 'app', category: 'finance', icon: '🪙' },
  'tradingview.exe':                    { name: 'TradingView',         type: 'app', category: 'finance', icon: '📈' },
  'metatrader4.exe':                    { name: 'MetaTrader 4',        type: 'app', category: 'finance', icon: '📊' },
  'terminal.exe':                       { name: 'MetaTrader',          type: 'app', category: 'finance', icon: '📊' },
  'metatrader5.exe':                    { name: 'MetaTrader 5',        type: 'app', category: 'finance', icon: '📊' },
  'terminal64.exe':                     { name: 'MetaTrader 5',        type: 'app', category: 'finance', icon: '📊' },
  'thinkorswim.exe':                    { name: 'thinkorswim',         type: 'app', category: 'finance', icon: '📈' },
  'tost.exe':                           { name: 'thinkorswim',         type: 'app', category: 'finance', icon: '📈' },
  'robinhood.exe':                      { name: 'Robinhood',           type: 'app', category: 'finance', icon: '🐦' },
  'revolut.exe':                        { name: 'Revolut',             type: 'app', category: 'finance', icon: '💳' },
  'paypal.exe':                         { name: 'PayPal',              type: 'app', category: 'finance', icon: '💸' },
  'etoro.exe':                          { name: 'eToro',               type: 'app', category: 'finance', icon: '📈' },
  'interactivebrokers.exe':             { name: 'Interactive Brokers', type: 'app', category: 'finance', icon: '📊' },
  'tws.exe':                            { name: 'Trader Workstation',  type: 'app', category: 'finance', icon: '📊' },
  'ibgateway.exe':                      { name: 'IB Gateway',          type: 'app', category: 'finance', icon: '📊' },
  'ninjatrader.exe':                    { name: 'NinjaTrader',         type: 'app', category: 'finance', icon: '🥷' },
  'ninjatrader8.exe':                   { name: 'NinjaTrader 8',       type: 'app', category: 'finance', icon: '🥷' },
  'ctrader.exe':                        { name: 'cTrader',             type: 'app', category: 'finance', icon: '📈' },
  'dukascopy.exe':                      { name: 'Dukascopy',           type: 'app', category: 'finance', icon: '🇨🇭' },
  'oanda.exe':                          { name: 'OANDA',               type: 'app', category: 'finance', icon: '💱' },
  'fxcm.exe':                           { name: 'FXCM',                type: 'app', category: 'finance', icon: '💱' },
  'saxotrader.exe':                     { name: 'SaxoTrader',          type: 'app', category: 'finance', icon: '📈' },
  'questrade.exe':                      { name: 'Questrade',           type: 'app', category: 'finance', icon: '🇨🇦' },
  'webull.exe':                         { name: 'Webull',              type: 'app', category: 'finance', icon: '🐂' },
  'tdameritrade.exe':                   { name: 'TD Ameritrade',       type: 'app', category: 'finance', icon: '💚' },
  'schwab.exe':                         { name: 'Charles Schwab',      type: 'app', category: 'finance', icon: '💙' },
  'fidelity.exe':                       { name: 'Fidelity',            type: 'app', category: 'finance', icon: '🔵' },
  'etrade.exe':                         { name: 'E*TRADE',             type: 'app', category: 'finance', icon: '🟢' },
  'kraken.exe':                         { name: 'Kraken',              type: 'app', category: 'finance', icon: '🐙' },

  // ─── PHOTO & VIDEO MANAGEMENT (~45) ────────────────────────────────────────
  'googlephotos.exe':                   { name: 'Google Photos',       type: 'app', category: 'photo-video', icon: '📷' },
  'lightroom.exe':                      { name: 'Adobe Lightroom',     type: 'app', category: 'photo-video', icon: '📸' },
  'lightroomcc.exe':                    { name: 'Lightroom CC',        type: 'app', category: 'photo-video', icon: '📸' },
  'iphoto.exe':                         { name: 'iPhoto',              type: 'app', category: 'photo-video', icon: '📷' },
  'picasa.exe':                         { name: 'Picasa',              type: 'app', category: 'photo-video', icon: '📷' },
  'faststone.exe':                      { name: 'FastStone',           type: 'app', category: 'photo-video', icon: '🖼️' },
  'fsviewer.exe':                       { name: 'FastStone Viewer',    type: 'app', category: 'photo-video', icon: '🖼️' },
  'irfanview.exe':                      { name: 'IrfanView',           type: 'app', category: 'photo-video', icon: '🖼️' },
  'iview.exe':                          { name: 'IrfanView',           type: 'app', category: 'photo-video', icon: '🖼️' },
  'xnview.exe':                         { name: 'XnView',              type: 'app', category: 'photo-video', icon: '🖼️' },
  'xnviewmp.exe':                       { name: 'XnView MP',           type: 'app', category: 'photo-video', icon: '🖼️' },
  'acdsee.exe':                         { name: 'ACDSee',              type: 'app', category: 'photo-video', icon: '🖼️' },
  'paint.net.exe':                      { name: 'Paint.NET',           type: 'app', category: 'photo-video', icon: '🎨' },
  'paintnet.exe':                       { name: 'Paint.NET',           type: 'app', category: 'photo-video', icon: '🎨' },
  'photoscape.exe':                     { name: 'PhotoScape',          type: 'app', category: 'photo-video', icon: '🖼️' },
  'photofiltre.exe':                    { name: 'PhotoFiltre',         type: 'app', category: 'photo-video', icon: '🖼️' },
  'rawtherapee.exe':                    { name: 'RawTherapee',         type: 'app', category: 'photo-video', icon: '🖼️' },
  'darktable.exe':                      { name: 'Darktable',             type: 'app', category: 'photo-video', icon: '🖼️' },
  'darktable-cli.exe':                  { name: 'Darktable',             type: 'app', category: 'photo-video', icon: '🖼️' },
  'digikam.exe':                        { name: 'digiKam',             type: 'app', category: 'photo-video', icon: '📷' },
  'shotwell.exe':                       { name: 'Shotwell',            type: 'app', category: 'photo-video', icon: '📷' },
  'fspot.exe':                          { name: 'F-Spot',              type: 'app', category: 'photo-video', icon: '📷' },
  'geeqie.exe':                         { name: 'Geeqie',              type: 'app', category: 'photo-video', icon: '🖼️' },
  'exiftool.exe':                       { name: 'ExifTool',            type: 'app', category: 'photo-video', icon: '📷' },
  'imagemagick.exe':                    { name: 'ImageMagick',         type: 'app', category: 'photo-video', icon: '🪄' },
  'magick.exe':                         { name: 'ImageMagick',         type: 'app', category: 'photo-video', icon: '🪄' },
  'ffmpeg.exe':                         { name: 'FFmpeg',              type: 'app', category: 'photo-video', icon: '🎬' },
  'handbrake.exe':                      { name: 'HandBrake',           type: 'app', category: 'photo-video', icon: '📀' },
  'makemkv.exe':                        { name: 'MakeMKV',             type: 'app', category: 'photo-video', icon: '📀' },
  'dvdflick.exe':                       { name: 'DVD Flick',           type: 'app', category: 'photo-video', icon: '📀' },
  'dvdshrink.exe':                      { name: 'DVD Shrink',          type: 'app', category: 'photo-video', icon: '📀' },
  'formatfactory.exe':                  { name: 'Format Factory',      type: 'app', category: 'photo-video', icon: '🔄' },
  'freemake.exe':                       { name: 'Freemake',            type: 'app', category: 'photo-video', icon: '🎬' },
  'anydvd.exe':                         { name: 'AnyDVD',              type: 'app', category: 'photo-video', icon: '📀' },
  'clonedvd.exe':                       { name: 'CloneDVD',            type: 'app', category: 'photo-video', icon: '📀' },
  'movavi.exe':                         { name: 'Movavi',              type: 'app', category: 'photo-video', icon: '🎬' },
  'wondershare.exe':                    { name: 'Wondershare',         type: 'app', category: 'photo-video', icon: '✨' },
  'filmora.exe':                        { name: 'Filmora',             type: 'app', category: 'photo-video', icon: '🎬' },
  'camtasia.exe':                       { name: 'Camtasia',            type: 'app', category: 'photo-video', icon: '📹' },
  'snagit.exe':                         { name: 'Snagit',              type: 'app', category: 'photo-video', icon: '📸' },
  'bandicam.exe':                       { name: 'Bandicam',            type: 'app', category: 'photo-video', icon: '📹' },
  'fraps.exe':                          { name: 'Fraps',               type: 'app', category: 'photo-video', icon: '📹' },
  'dxtory.exe':                         { name: 'Dxtory',              type: 'app', category: 'photo-video', icon: '📹' },
  'mirillis.exe':                       { name: 'Mirillis Action!',    type: 'app', category: 'photo-video', icon: '📹' },
  'action.exe':                         { name: 'Action!',             type: 'app', category: 'photo-video', icon: '📹' },
  'shadowplay.exe':                     { name: 'NVIDIA ShadowPlay',   type: 'app', category: 'photo-video', icon: '📹' },

  // ─── CAD, ENGINEERING & 3D MODELING (~30) ───────────────────────────────────
  'autocad.exe':                        { name: 'AutoCAD',             type: 'app', category: 'cad', icon: '📐' },
  'acad.exe':                           { name: 'AutoCAD',             type: 'app', category: 'cad', icon: '📐' },
  'solidworks.exe':                     { name: 'SOLIDWORKS',          type: 'app', category: 'cad', icon: '⚙️' },
  'sldworks.exe':                       { name: 'SOLIDWORKS',          type: 'app', category: 'cad', icon: '⚙️' },
  'fusion360.exe':                      { name: 'Fusion 360',          type: 'app', category: 'cad', icon: '🔧' },
  'fusion.exe':                         { name: 'Fusion 360',          type: 'app', category: 'cad', icon: '🔧' },
  'sketchup.exe':                       { name: 'SketchUp',            type: 'app', category: 'cad', icon: '📐' },
  'stylebuilder.exe':                   { name: 'SketchUp',            type: 'app', category: 'cad', icon: '📐' },
  'revit.exe':                          { name: 'Revit',               type: 'app', category: 'cad', icon: '🏗️' },
  'freecad.exe':                        { name: 'FreeCAD',             type: 'app', category: 'cad', icon: '🔧' },
  'tinkercad.exe':                      { name: 'Tinkercad',           type: 'app', category: 'cad', icon: '🧊' },
  'onshape.exe':                        { name: 'Onshape',             type: 'app', category: 'cad', icon: '☁️' },
  'rhino.exe':                          { name: 'Rhinoceros',          type: 'app', category: 'cad', icon: '🦏' },
  'rhinoceros.exe':                     { name: 'Rhinoceros',          type: 'app', category: 'cad', icon: '🦏' },
  'catia.exe':                          { name: 'CATIA',               type: 'app', category: 'cad', icon: '✈️' },
  'nx.exe':                             { name: 'Siemens NX',          type: 'app', category: 'cad', icon: '⚙️' },
  'inventor.exe':                       { name: 'Autodesk Inventor',   type: 'app', category: 'cad', icon: '⚙️' },
  'cinema4d.exe':                       { name: 'Cinema 4D',           type: 'app', category: 'cad', icon: '🎬' },
  'c4d.exe':                            { name: 'Cinema 4D',           type: 'app', category: 'cad', icon: '🎬' },
  'modo.exe':                           { name: 'Modo',                type: 'app', category: 'cad', icon: '🎨' },
  'marvelousdesigner.exe':              { name: 'Marvelous Designer',  type: 'app', category: 'cad', icon: '👗' },
  'clo3d.exe':                          { name: 'CLO 3D',              type: 'app', category: 'cad', icon: '👔' },
  'keyshot.exe':                        { name: 'KeyShot',             type: 'app', category: 'cad', icon: '🔑' },
  'lumion.exe':                         { name: 'Lumion',              type: 'app', category: 'cad', icon: '🏠' },
  'enscape.exe':                        { name: 'Enscape',             type: 'app', category: 'cad', icon: '🏠' },
  'vray.exe':                           { name: 'V-Ray',               type: 'app', category: 'cad', icon: '💡' },
  'corona.exe':                         { name: 'Corona Renderer',     type: 'app', category: 'cad', icon: '☀️' },
  'octane.exe':                         { name: 'Octane Render',       type: 'app', category: 'cad', icon: '⚡' },

  // ─── SCIENTIFIC, ACADEMIC & DATA (~35) ───────────────────────────────────────
  'matlab.exe':                         { name: 'MATLAB',              type: 'app', category: 'scientific', icon: '📊' },
  'matlabengine.exe':                   { name: 'MATLAB',              type: 'app', category: 'scientific', icon: '📊' },
  'mathematica.exe':                    { name: 'Mathematica',         type: 'app', category: 'scientific', icon: '🔢' },
  'wolfram.exe':                        { name: 'Wolfram',             type: 'app', category: 'scientific', icon: '🔢' },
  'maple.exe':                          { name: 'Maple',               type: 'app', category: 'scientific', icon: '🍁' },
  'originlab.exe':                      { name: 'OriginLab',           type: 'app', category: 'scientific', icon: '📈' },
  'spss.exe':                           { name: 'SPSS',                type: 'app', category: 'scientific', icon: '📊' },
  'stats.exe':                          { name: 'SPSS',                type: 'app', category: 'scientific', icon: '📊' },
  'sas.exe':                            { name: 'SAS',                 type: 'app', category: 'scientific', icon: '📊' },
  'stata.exe':                          { name: 'Stata',               type: 'app', category: 'scientific', icon: '📊' },
  'rstudio.exe':                        { name: 'RStudio',             type: 'app', category: 'scientific', icon: '📊' },
  'r.exe':                              { name: 'R',                   type: 'app', category: 'scientific', icon: '📊' },
  'rgui.exe':                           { name: 'R',                   type: 'app', category: 'scientific', icon: '📊' },
  'rstudioserver.exe':                  { name: 'RStudio Server',      type: 'app', category: 'scientific', icon: '📊' },
  'jupyter.exe':                        { name: 'Jupyter',             type: 'app', category: 'scientific', icon: '📓' },
  'jupyter-lab.exe':                    { name: 'JupyterLab',          type: 'app', category: 'scientific', icon: '📓' },
  'jupyter-notebook.exe':               { name: 'Jupyter Notebook',    type: 'app', category: 'scientific', icon: '📓' },
  'anaconda.exe':                       { name: 'Anaconda',            type: 'app', category: 'scientific', icon: '🐍' },
  'condabin.exe':                       { name: 'Anaconda',            type: 'app', category: 'scientific', icon: '🐍' },
  'texworks.exe':                       { name: 'TeXworks',            type: 'app', category: 'scientific', icon: '📜' },
  'texstudio.exe':                      { name: 'TeXstudio',           type: 'app', category: 'scientific', icon: '📜' },
  'miktex.exe':                         { name: 'MiKTeX',              type: 'app', category: 'scientific', icon: '📜' },
  'lyx.exe':                            { name: 'LyX',                 type: 'app', category: 'scientific', icon: '📜' },
  'jabref.exe':                         { name: 'JabRef',              type: 'app', category: 'scientific', icon: '📚' },
  'mendeley.exe':                       { name: 'Mendeley',            type: 'app', category: 'scientific', icon: '📚' },
  'zotero.exe':                         { name: 'Zotero',              type: 'app', category: 'scientific', icon: '📚' },
  'citavi.exe':                         { name: 'Citavi',              type: 'app', category: 'scientific', icon: '📚' },
  'endnote.exe':                        { name: 'EndNote',             type: 'app', category: 'scientific', icon: '📚' },
  'papers.exe':                         { name: 'Papers',              type: 'app', category: 'scientific', icon: '📄' },
  'readcube.exe':                       { name: 'ReadCube',            type: 'app', category: 'scientific', icon: '📦' },
  'scilab.exe':                         { name: 'Scilab',              type: 'app', category: 'scientific', icon: '🔬' },
  'octave.exe':                         { name: 'GNU Octave',          type: 'app', category: 'scientific', icon: '🔢' },
  'gnuplot.exe':                        { name: 'Gnuplot',             type: 'app', category: 'scientific', icon: '📈' },
  'chemcraft.exe':                      { name: 'ChemCraft',           type: 'app', category: 'scientific', icon: '⚗️' },
  'avogadro.exe':                       { name: 'Avogadro',            type: 'app', category: 'scientific', icon: '⚗️' },

  // ─── TERMINAL & SSH (~25) ──────────────────────────────────────────────────
  'putty.exe':                          { name: 'PuTTY',               type: 'app', category: 'terminal', icon: '💻' },
  'puttytel.exe':                       { name: 'PuTTYtel',            type: 'app', category: 'terminal', icon: '💻' },
  'kitty.exe':                          { name: 'KiTTY',               type: 'app', category: 'terminal', icon: '🐱' },
  'kitty_portable.exe':                 { name: 'KiTTY',               type: 'app', category: 'terminal', icon: '🐱' },
  'termius.exe':                        { name: 'Termius',             type: 'app', category: 'terminal', icon: '📱' },
  'mobaxterm.exe':                      { name: 'MobaXterm',           type: 'app', category: 'terminal', icon: '💻' },
  'mobaxterm_personal.exe':             { name: 'MobaXterm',           type: 'app', category: 'terminal', icon: '💻' },
  'securecrt.exe':                      { name: 'SecureCRT',           type: 'app', category: 'terminal', icon: '🔒' },
  'xshell.exe':                         { name: 'Xshell',              type: 'app', category: 'terminal', icon: '💻' },
  'xshellcore.exe':                     { name: 'Xshell',              type: 'app', category: 'terminal', icon: '💻' },
  'zoc.exe':                            { name: 'ZOC Terminal',        type: 'app', category: 'terminal', icon: '💻' },
  'royaltsv4.exe':                      { name: 'Royal TS V4',         type: 'app', category: 'terminal', icon: '👑' },
  'tabby.exe':                          { name: 'Tabby',               type: 'app', category: 'terminal', icon: '🐱' },
  'electerm.exe':                       { name: 'Electerm',            type: 'app', category: 'terminal', icon: '⚡' },
  'extraterm.exe':                      { name: 'Extraterm',           type: 'app', category: 'terminal', icon: '👽' },
  'cmder.exe':                          { name: 'Cmder',               type: 'app', category: 'terminal', icon: '💻' },
  'conemu.exe':                         { name: 'ConEmu',              type: 'app', category: 'terminal', icon: '💻' },
  'console.exe':                        { name: 'Console',             type: 'app', category: 'terminal', icon: '💻' },
  'terminus.exe':                       { name: 'Terminus',            type: 'app', category: 'terminal', icon: '🌐' },
  'winscp.exe':                         { name: 'WinSCP',              type: 'app', category: 'terminal', icon: '📂' },
  'filezilla.exe':                      { name: 'FileZilla',           type: 'app', category: 'terminal', icon: '🐆' },
  'filezillaserver.exe':                { name: 'FileZilla Server',    type: 'app', category: 'terminal', icon: '🐆' },
  'coreftp.exe':                        { name: 'Core FTP',            type: 'app', category: 'terminal', icon: '📂' },
  'smartftp.exe':                       { name: 'SmartFTP',            type: 'app', category: 'terminal', icon: '📂' },
  'flashfxp.exe':                       { name: 'FlashFXP',            type: 'app', category: 'terminal', icon: '⚡' },

  // ─── ADDITIONAL IDEs & EDITORS (~35) ───────────────────────────────────────
  'eclipse.exe':                        { name: 'Eclipse',             type: 'app', category: 'editor', icon: '🌑' },
  'eclipsec.exe':                       { name: 'Eclipse',             type: 'app', category: 'editor', icon: '🌑' },
  'netbeans.exe':                       { name: 'NetBeans',            type: 'app', category: 'editor', icon: '📦' },
  'netbeans64.exe':                     { name: 'NetBeans',            type: 'app', category: 'editor', icon: '📦' },
  'komodo.exe':                         { name: 'Komodo IDE',          type: 'app', category: 'editor', icon: '🦎' },
  'brackets.exe':                       { name: 'Brackets',            type: 'app', category: 'editor', icon: '{}' },
  'geany.exe':                          { name: 'Geany',               type: 'app', category: 'editor', icon: '📄' },
  'bluej.exe':                          { name: 'BlueJ',               type: 'app', category: 'editor', icon: '🔵' },
  'drracket.exe':                       { name: 'DrRacket',            type: 'app', category: 'editor', icon: '🏓' },
  'scratch.exe':                        { name: 'Scratch',             type: 'app', category: 'editor', icon: '🐱' },
  'scratch3.exe':                       { name: 'Scratch 3',           type: 'app', category: 'editor', icon: '🐱' },
  'processing.exe':                     { name: 'Processing',          type: 'app', category: 'editor', icon: '🎨' },
  'pde.exe':                            { name: 'Processing',          type: 'app', category: 'editor', icon: '🎨' },
  'arduino.exe':                        { name: 'Arduino IDE',         type: 'app', category: 'editor', icon: '🔌' },
  'arduino-builder.exe':                { name: 'Arduino Builder',     type: 'app', category: 'editor', icon: '🔌' },
  'platformio.exe':                     { name: 'PlatformIO',          type: 'app', category: 'editor', icon: '🛠️' },
  'pio.exe':                            { name: 'PlatformIO',          type: 'app', category: 'editor', icon: '🛠️' },
  'espressif.exe':                      { name: 'Espressif IDF',       type: 'app', category: 'editor', icon: '📡' },
  'idf.exe':                            { name: 'ESP-IDF',             type: 'app', category: 'editor', icon: '📡' },
  'stm32cubeide.exe':                   { name: 'STM32CubeIDE',        type: 'app', category: 'editor', icon: '🔧' },
  'truestudio.exe':                     { name: 'TrueSTUDIO',          type: 'app', category: 'editor', icon: '🔧' },
  'atmelstudio.exe':                    { name: 'Atmel Studio',        type: 'app', category: 'editor', icon: '🔧' },
  'mplabx.exe':                         { name: 'MPLAB X',             type: 'app', category: 'editor', icon: '🔬' },
  'mcuxpressoide.exe':                  { name: 'MCUXpresso',          type: 'app', category: 'editor', icon: '🔧' },
  'e2studio.exe':                       { name: 'e2 studio',           type: 'app', category: 'editor', icon: '🔧' },
  'kendryteide.exe':                    { name: 'Kendryte IDE',        type: 'app', category: 'editor', icon: '🧠' },
  'codeblocks.exe':                     { name: 'Code::Blocks',        type: 'app', category: 'editor', icon: '⬜' },
  'codelite.exe':                       { name: 'CodeLite',            type: 'app', category: 'editor', icon: '💎' },
  'kdevelop.exe':                       { name: 'KDevelop',            type: 'app', category: 'editor', icon: '🔧' },
  'anjuta.exe':                         { name: 'Anjuta',              type: 'app', category: 'editor', icon: '📐' },
  'monodevelop.exe':                    { name: 'MonoDevelop',         type: 'app', category: 'editor', icon: '🔵' },
  'sharpdevelop.exe':                   { name: 'SharpDevelop',        type: 'app', category: 'editor', icon: '🔷' },
  'linqpad.exe':                        { name: 'LINQPad',             type: 'app', category: 'editor', icon: '🔷' },
  'linqpad5.exe':                       { name: 'LINQPad',             type: 'app', category: 'editor', icon: '🔷' },

  // ─── DEVOPS, CONTAINER & VIRTUALIZATION (~25) ───────────────────────────────
  'docker.exe':                         { name: 'Docker',              type: 'app', category: 'devops', icon: '🐳' },
  'dockercli.exe':                      { name: 'Docker CLI',          type: 'app', category: 'devops', icon: '🐳' },
  'kubectl.exe':                        { name: 'kubectl',             type: 'app', category: 'devops', icon: '☸️' },
  'minikube.exe':                       { name: 'Minikube',            type: 'app', category: 'devops', icon: '⛏️' },
  'kind.exe':                           { name: 'kind',                type: 'app', category: 'devops', icon: '🔧' },
  'rancher.exe':                        { name: 'Rancher Desktop',     type: 'app', category: 'devops', icon: '🐮' },
  'rancherdesktop.exe':                 { name: 'Rancher Desktop',     type: 'app', category: 'devops', icon: '🐮' },
  'openshift.exe':                      { name: 'OpenShift',           type: 'app', category: 'devops', icon: '☸️' },
  'oc.exe':                             { name: 'OpenShift CLI',       type: 'app', category: 'devops', icon: '☸️' },
  'helm.exe':                           { name: 'Helm',                type: 'app', category: 'devops', icon: '⛵' },
  'terraform.exe':                      { name: 'Terraform',           type: 'app', category: 'devops', icon: '🏗️' },
  'pulumi.exe':                         { name: 'Pulumi',              type: 'app', category: 'devops', icon: '☁️' },
  'vagrant.exe':                        { name: 'Vagrant',             type: 'app', category: 'devops', icon: '📦' },
  'vagrantvmware.exe':                  { name: 'Vagrant VMware',      type: 'app', category: 'devops', icon: '📦' },
  'packer.exe':                         { name: 'Packer',              type: 'app', category: 'devops', icon: '📦' },
  'consul.exe':                         { name: 'Consul',              type: 'app', category: 'devops', icon: '🔒' },
  'vault.exe':                          { name: 'Vault',               type: 'app', category: 'devops', icon: '🏛️' },
  'nomad.exe':                          { name: 'Nomad',               type: 'app', category: 'devops', icon: '🏜️' },
  'ansible.exe':                        { name: 'Ansible',             type: 'app', category: 'devops', icon: '📜' },
  'awx.exe':                            { name: 'AWX',                 type: 'app', category: 'devops', icon: '📜' },
  'jenkins.exe':                        { name: 'Jenkins',             type: 'app', category: 'devops', icon: '🤵' },
  'hudson.exe':                         { name: 'Hudson',              type: 'app', category: 'devops', icon: '🤵' },
  'teamcity.exe':                       { name: 'TeamCity',            type: 'app', category: 'devops', icon: '🏙️' },
  'bamboo.exe':                         { name: 'Bamboo',              type: 'app', category: 'devops', icon: '🎋' },
  'circleci.exe':                       { name: 'CircleCI',            type: 'app', category: 'devops', icon: '⭕' },

  // ─── DISK & BACKUP (~25) ───────────────────────────────────────────────────
  'acronis.exe':                        { name: 'Acronis True Image',  type: 'app', category: 'backup', icon: '🛡️' },
  'acronistih.exe':                     { name: 'Acronis',             type: 'app', category: 'backup', icon: '🛡️' },
  'macrium.exe':                        { name: 'Macrium Reflect',     type: 'app', category: 'backup', icon: '💿' },
  'reflect.exe':                        { name: 'Macrium Reflect',     type: 'app', category: 'backup', icon: '💿' },
  'partitionwizard.exe':                { name: 'Partition Wizard',    type: 'app', category: 'backup', icon: '🧙' },
  'aomei.exe':                          { name: 'AOMEI Backupper',     type: 'app', category: 'backup', icon: '💾' },
  'backupper.exe':                      { name: 'AOMEI Backupper',     type: 'app', category: 'backup', icon: '💾' },
  'clonezilla.exe':                     { name: 'Clonezilla',          type: 'app', category: 'backup', icon: '🐉' },
  'easeus.exe':                         { name: 'EaseUS Todo Backup',  type: 'app', category: 'backup', icon: '💾' },
  'todo_backup.exe':                    { name: 'EaseUS Todo',         type: 'app', category: 'backup', icon: '💾' },
  'paragon.exe':                        { name: 'Paragon Backup',      type: 'app', category: 'backup', icon: '💿' },
  'paragonharddiskmanager.exe':         { name: 'Paragon HDM',         type: 'app', category: 'backup', icon: '💿' },
  'activebootdisk.exe':                 { name: 'Active Boot Disk',    type: 'app', category: 'backup', icon: '💿' },
  'runtime.exe':                        { name: 'Runtime Software',    type: 'app', category: 'backup', icon: '⏱️' },
  'r-studio.exe':                       { name: 'R-Studio',            type: 'app', category: 'backup', icon: '🔧' },
  'diskgenius.exe':                     { name: 'DiskGenius',          type: 'app', category: 'backup', icon: '🔧' },
  'partitionguru.exe':                  { name: 'PartitionGuru',       type: 'app', category: 'backup', icon: '🔧' },
  'testdisk.exe':                       { name: 'TestDisk',            type: 'app', category: 'backup', icon: '🔍' },
  'photorec.exe':                       { name: 'PhotoRec',            type: 'app', category: 'backup', icon: '📷' },
  'recuva.exe':                         { name: 'Recuva',              type: 'app', category: 'backup', icon: '🔍' },
  'recuva64.exe':                       { name: 'Recuva',              type: 'app', category: 'backup', icon: '🔍' },
  'undelete.exe':                       { name: 'Undelete',            type: 'app', category: 'backup', icon: '🗑️' },
  'diskdrill.exe':                      { name: 'Disk Drill',          type: 'app', category: 'backup', icon: '🔩' },
  'diskdrill64.exe':                    { name: 'Disk Drill',          type: 'app', category: 'backup', icon: '🔩' },
  'stellarphoenix.exe':                 { name: 'Stellar Phoenix',     type: 'app', category: 'backup', icon: '⭐' },

  // ─── FILE MANAGERS (~20) ───────────────────────────────────────────────────
  'totalcmd.exe':                       { name: 'Total Commander',     type: 'app', category: 'file-manager', icon: '📂' },
  'totalcmd64.exe':                     { name: 'Total Commander',     type: 'app', category: 'file-manager', icon: '📂' },
  'directoryopus.exe':                  { name: 'Directory Opus',      type: 'app', category: 'file-manager', icon: '📂' },
  'dopus.exe':                          { name: 'Directory Opus',      type: 'app', category: 'file-manager', icon: '📂' },
  'xyplorer.exe':                       { name: 'XYplorer',            type: 'app', category: 'file-manager', icon: '📂' },
  'onecommander.exe':                   { name: 'One Commander',       type: 'app', category: 'file-manager', icon: '📂' },
  'filesuwp.exe':                       { name: 'Files UWP',           type: 'app', category: 'file-manager', icon: '📂' },
  'fman.exe':                           { name: 'fman',                type: 'app', category: 'file-manager', icon: '📂' },
  'midnightcommander.exe':              { name: 'Midnight Commander',  type: 'app', category: 'file-manager', icon: '🌙' },
  'mc.exe':                             { name: 'Midnight Commander',  type: 'app', category: 'file-manager', icon: '🌙' },
  'far.exe':                            { name: 'Far Manager',         type: 'app', category: 'file-manager', icon: '💻' },
  'doublecmd.exe':                      { name: 'Double Commander',    type: 'app', category: 'file-manager', icon: '📂' },
  'freecommander.exe':                  { name: 'FreeCommander',       type: 'app', category: 'file-manager', icon: '📂' },
  'q-dir.exe':                          { name: 'Q-Dir',               type: 'app', category: 'file-manager', icon: '📂' },
  'explorer++.exe':                     { name: 'Explorer++',          type: 'app', category: 'file-manager', icon: '📂' },
  'speedcommander.exe':                 { name: 'SpeedCommander',      type: 'app', category: 'file-manager', icon: '⚡' },
  'altap.exe':                          { name: 'Altap Salamander',    type: 'app', category: 'file-manager', icon: '🦎' },
  'salamand.exe':                       { name: 'Salamander',          type: 'app', category: 'file-manager', icon: '🦎' },
  'multiarc.exe':                       { name: 'MultiArc',            type: 'app', category: 'file-manager', icon: '📦' },
  'unrealcommander.exe':                { name: 'Unreal Commander',    type: 'app', category: 'file-manager', icon: '📂' },

  // ─── EMAIL CLIENTS (~15) ─────────────────────────────────────────────────────
  'emclient.exe':                       { name: 'eM Client',           type: 'app', category: 'email', icon: '📧' },
  'mailbird.exe':                       { name: 'Mailbird',            type: 'app', category: 'email', icon: '🐦' },
  'mailspring.exe':                     { name: 'Mailspring',          type: 'app', category: 'email', icon: '📧' },
  'spark.exe':                          { name: 'Spark',               type: 'app', category: 'email', icon: '✨' },
  'bluemail.exe':                       { name: 'BlueMail',            type: 'app', category: 'email', icon: '🔵' },
  'newton.exe':                         { name: 'Newton Mail',         type: 'app', category: 'email', icon: '🍎' },
  'foxmail.exe':                        { name: 'Foxmail',             type: 'app', category: 'email', icon: '🦊' },
  'thebat.exe':                         { name: 'The Bat!',            type: 'app', category: 'email', icon: '🦇' },
  'postbox.exe':                        { name: 'Postbox',             type: 'app', category: 'email', icon: '📮' },
  'pegasus.exe':                        { name: 'Pegasus Mail',        type: 'app', category: 'email', icon: '🦄' },
  'becky.exe':                          { name: 'Becky Internet Mail', type: 'app', category: 'email', icon: '📧' },
  'claws-mail.exe':                     { name: 'Claws Mail',          type: 'app', category: 'email', icon: '🐾' },
  'sylpheed.exe':                       { name: 'Sylpheed',            type: 'app', category: 'email', icon: '🦋' },
  'geary.exe':                          { name: 'Geary',               type: 'app', category: 'email', icon: '📧' },
  'evolution.exe':                      { name: 'Evolution',           type: 'app', category: 'email', icon: '🐘' },

  // ─── CALENDAR & TASK MANAGEMENT (~15) ──────────────────────────────────────
  'fantastical.exe':                    { name: 'Fantastical',         type: 'app', category: 'calendar', icon: '📅' },
  'calendly.exe':                       { name: 'Calendly',            type: 'app', category: 'calendar', icon: '📅' },
  'remember.exe':                       { name: 'Remember The Milk',   type: 'app', category: 'calendar', icon: '🥛' },
  'wunderlist.exe':                     { name: 'Wunderlist',          type: 'app', category: 'calendar', icon: '⭐' },
  'trello.exe':                         { name: 'Trello',              type: 'app', category: 'calendar', icon: '📋' },
  'asana.exe':                          { name: 'Asana',               type: 'app', category: 'calendar', icon: '🧘' },
  'monday.exe':                         { name: 'monday.com',          type: 'app', category: 'calendar', icon: '📅' },
  'clickup.exe':                        { name: 'ClickUp',             type: 'app', category: 'calendar', icon: '☝️' },
  'notioncalendar.exe':                 { name: 'Notion Calendar',     type: 'app', category: 'calendar', icon: '📅' },
  'cron.exe':                           { name: 'Cron',                type: 'app', category: 'calendar', icon: '⏰' },
  'amie.exe':                           { name: 'Amie',                type: 'app', category: 'calendar', icon: '💗' },
  'sunsama.exe':                        { name: 'Sunsama',             type: 'app', category: 'calendar', icon: '🌅' },
  'akiflow.exe':                        { name: 'Akiflow',             type: 'app', category: 'calendar', icon: '🌊' },
  'routine.exe':                        { name: 'Routine',             type: 'app', category: 'calendar', icon: '🔄' },
  'motion.exe':                         { name: 'Motion',              type: 'app', category: 'calendar', icon: '⚡' },

  // ─── MUSIC PRODUCTION EXTRA (~20) ──────────────────────────────────────────
  'protools.exe':                       { name: 'Pro Tools',           type: 'app', category: 'audio', icon: '🎛️' },
  'protoolsfirst.exe':                  { name: 'Pro Tools First',     type: 'app', category: 'audio', icon: '🎛️' },
  'bitwigstudio.exe':                   { name: 'Bitwig Studio',       type: 'app', category: 'audio', icon: '⚡' },
  'bitwig.exe':                         { name: 'Bitwig',              type: 'app', category: 'audio', icon: '⚡' },
  'lmms.exe':                           { name: 'LMMS',                type: 'app', category: 'audio', icon: '🎹' },
  'ardour.exe':                         { name: 'Ardour',              type: 'app', category: 'audio', icon: '🎙️' },
  'tracktion.exe':                      { name: 'Tracktion',           type: 'app', category: 'audio', icon: '🎵' },
  'waveform.exe':                       { name: 'Waveform',            type: 'app', category: 'audio', icon: '〰️' },
  'reason.exe':                         { name: 'Reason',              type: 'app', category: 'audio', icon: '🧠' },
  'maschine.exe':                       { name: 'Maschine',            type: 'app', category: 'audio', icon: '🎛️' },
  'nativeaccess.exe':                   { name: 'Native Access',       type: 'app', category: 'audio', icon: '🎛️' },
  'komplete.exe':                       { name: 'Komplete',            type: 'app', category: 'audio', icon: '🎹' },
  'serato.exe':                         { name: 'Serato DJ',           type: 'app', category: 'audio', icon: '🎧' },
  'djpro.exe':                          { name: 'djay Pro',            type: 'app', category: 'audio', icon: '🎧' },
  'rekordbox.exe':                      { name: 'Rekordbox',           type: 'app', category: 'audio', icon: '📦' },
  'virtualdj.exe':                      { name: 'VirtualDJ',           type: 'app', category: 'audio', icon: '🎧' },
  'mixxx.exe':                          { name: 'Mixxx',               type: 'app', category: 'audio', icon: '🎚️' },
  'traktor.exe':                        { name: 'Traktor',             type: 'app', category: 'audio', icon: '🎛️' },
  'splice.exe':                         { name: 'Splice',              type: 'app', category: 'audio', icon: '✂️' },

  // ─── MISC PRODUCTIVITY & UTILITIES (~20) ───────────────────────────────────
  'ditto.exe':                          { name: 'Ditto',               type: 'app', category: 'utility', icon: '📋' },
  'clipboardfusion.exe':                { name: 'ClipboardFusion',     type: 'app', category: 'utility', icon: '📋' },
  'copyq.exe':                          { name: 'CopyQ',               type: 'app', category: 'utility', icon: '📋' },
  'phraseexpress.exe':                  { name: 'PhraseExpress',       type: 'app', category: 'utility', icon: '💬' },
  'autotext.exe':                       { name: 'AutoText',            type: 'app', category: 'utility', icon: '💬' },
  'textexpander.exe':                   { name: 'TextExpander',        type: 'app', category: 'utility', icon: '💬' },
  'espanso.exe':                        { name: 'Espanso',             type: 'app', category: 'utility', icon: '💬' },
  'aquaSnap.exe':                       { name: 'AquaSnap',            type: 'app', category: 'utility', icon: '💧' },
  'displayfusion.exe':                  { name: 'DisplayFusion',       type: 'app', category: 'utility', icon: '🖥️' },
  'actualwindowmanager.exe':            { name: 'Actual Window Manager',type: 'app', category: 'utility', icon: '🪟' },
  'ultramon.exe':                       { name: 'UltraMon',            type: 'app', category: 'utility', icon: '🖥️' },
  'nexusfont.exe':                      { name: 'NexusFont',           type: 'app', category: 'utility', icon: '🔤' },
  'fontbase.exe':                       { name: 'FontBase',            type: 'app', category: 'utility', icon: '🔤' },
  'colorzilla.exe':                     { name: 'ColorZilla',          type: 'app', category: 'utility', icon: '🎨' },
  'justcolorpicker.exe':                { name: 'Just Color Picker',   type: 'app', category: 'utility', icon: '🎨' },
  'everything.exe':                     { name: 'Everything',          type: 'app', category: 'utility', icon: '🔍' },
  'listary.exe':                        { name: 'Listary',             type: 'app', category: 'utility', icon: '🔍' },
  'wox.exe':                            { name: 'Wox',                 type: 'app', category: 'utility', icon: '🔍' },
  'ueli.exe':                           { name: 'Ueli',                type: 'app', category: 'utility', icon: '🔍' },
};
