/**
 * Extended Game Database — 500+ NEW popular games with unique emojis
 * Merged into PROCESS_DB via spread operator.
 */

export const EXTRA_GAMES = {
  // ─── FPS / TACTICAL SHOOTERS (new) ─────────────────────────────────────
  'insurgency2.exe':                    { name: 'Insurgency: Sandstorm',type: 'game', category: 'fps',     icon: '💥' },
  'payday3.exe':                        { name: 'PAYDAY 3',            type: 'game', category: 'fps',      icon: '💰' },
  'payday2.exe':                        { name: 'PAYDAY 2',            type: 'game', category: 'fps',      icon: '💰' },
  'left4dead2.exe':                     { name: 'Left 4 Dead 2',       type: 'game', category: 'fps',      icon: '🧟' },
  'l4d2.exe':                           { name: 'Left 4 Dead 2',       type: 'game', category: 'fps',      icon: '🧟' },
  'back4blood.exe':                     { name: 'Back 4 Blood',        type: 'game', category: 'fps',      icon: '🧟' },
  'zombiearmy4.exe':                    { name: 'Zombie Army 4',       type: 'game', category: 'fps',      icon: '💀' },
  'sniperelite5.exe':                   { name: 'Sniper Elite 5',      type: 'game', category: 'fps',      icon: '🎯' },
  'sniperelite4.exe':                   { name: 'Sniper Elite 4',      type: 'game', category: 'fps',      icon: '🎯' },
  'sniperelite3.exe':                   { name: 'Sniper Elite 3',      type: 'game', category: 'fps',      icon: '🎯' },
  'doom.exe':                           { name: 'DOOM Eternal',        type: 'game', category: 'fps',      icon: '😈' },
  'doometernal.exe':                    { name: 'DOOM Eternal',        type: 'game', category: 'fps',      icon: '😈' },
  'doom2016.exe':                       { name: 'DOOM (2016)',         type: 'game', category: 'fps',      icon: '😈' },
  'wolfensteiniithenewcolossus.exe':   { name: 'Wolfenstein II',      type: 'game', category: 'fps',      icon: '🐺' },
  'wolfensteinyoungblood.exe':          { name: 'Wolfenstein: Youngblood',type: 'game', category: 'fps',   icon: '🐺' },
  'borderlands3.exe':                   { name: 'Borderlands 3',       type: 'game', category: 'fps',      icon: '🎭' },
  'borderlands2.exe':                   { name: 'Borderlands 2',       type: 'game', category: 'fps',      icon: '🎭' },
  'tinytinaswonderlands.exe':           { name: "Tiny Tina's Wonderlands",type: 'game', category: 'fps',  icon: '🎲' },
  'bioshockinfinite.exe':               { name: 'BioShock Infinite',   type: 'game', category: 'fps',      icon: '🔮' },
  'bioshock2.exe':                      { name: 'BioShock 2',          type: 'game', category: 'fps',      icon: '🔮' },
  'bioshock.exe':                       { name: 'BioShock',            type: 'game', category: 'fps',      icon: '🔮' },
  'prey.exe':                           { name: 'Prey',                type: 'game', category: 'fps',      icon: '👽' },
  'deathloop.exe':                      { name: 'Deathloop',           type: 'game', category: 'fps',      icon: '🔄' },
  'ghostwiretokyo.exe':                 { name: 'Ghostwire: Tokyo',    type: 'game', category: 'fps',      icon: '👻' },
  'atomicheart.exe':                    { name: 'Atomic Heart',        type: 'game', category: 'fps',      icon: '🤖' },
  'metroexodus.exe':                    { name: 'Metro Exodus',        type: 'game', category: 'fps',      icon: '🚇' },
  'metrolastlight.exe':                 { name: 'Metro: Last Light',   type: 'game', category: 'fps',      icon: '🚇' },
  'metro2033.exe':                      { name: 'Metro 2033',          type: 'game', category: 'fps',      icon: '🚇' },
  'stalker2.exe':                       { name: 'S.T.A.L.K.E.R. 2',    type: 'game', category: 'fps',      icon: '☢️' },
  'stalkercallofpripyat.exe':           { name: 'S.T.A.L.K.E.R.: Call of Pripyat',type: 'game', category: 'fps', icon: '☢️' },
  'stalkerclearsky.exe':                { name: 'S.T.A.L.K.E.R.: Clear Sky',type: 'game', category: 'fps',  icon: '☢️' },
  'serioussam4.exe':                    { name: 'Serious Sam 4',       type: 'game', category: 'fps',      icon: '🤠' },
  'shadowwarrior3.exe':                 { name: 'Shadow Warrior 3',    type: 'game', category: 'fps',      icon: '⚔️' },
  'shadowwarrior2.exe':                 { name: 'Shadow Warrior 2',    type: 'game', category: 'fps',      icon: '⚔️' },
  'shadowwarrior.exe':                  { name: 'Shadow Warrior',      type: 'game', category: 'fps',      icon: '⚔️' },
  'rage2.exe':                          { name: 'RAGE 2',              type: 'game', category: 'fps',      icon: '😤' },
  'rage.exe':                           { name: 'RAGE',                type: 'game', category: 'fps',      icon: '😤' },
  'bulletstorm.exe':                    { name: 'Bulletstorm',         type: 'game', category: 'fps',      icon: '💨' },
  'painkiller.exe':                     { name: 'Painkiller',          type: 'game', category: 'fps',      icon: '💀' },
  'planetside2.exe':                    { name: 'PlanetSide 2',        type: 'game', category: 'fps',      icon: '🌍' },
  'resistance3.exe':                    { name: 'Resistance 3',        type: 'game', category: 'fps',      icon: '🛡️' },

  // ─── BATTLE ROYALE (new) ────────────────────────────────────────────
  'ringofelysium.exe':                  { name: 'Ring of Elysium',     type: 'game', category: 'battle-royale', icon: '💍' },
  'cuisine_royale.exe':                 { name: 'Cuisine Royale',      type: 'game', category: 'battle-royale', icon: '🍳' },
  'crsed.exe':                          { name: 'CRSED: F.O.A.D.',     type: 'game', category: 'battle-royale', icon: '💀' },
  'codm.exe':                           { name: 'Call of Duty: Mobile',type: 'game', category: 'battle-royale', icon: '📱' },
  'pubgmobile.exe':                     { name: 'PUBG Mobile',         type: 'game', category: 'battle-royale', icon: '📱' },
  'fortnitemobile.exe':                 { name: 'Fortnite Mobile',     type: 'game', category: 'battle-royale', icon: '📱' },
  'garenafreefire.exe':                 { name: 'Garena Free Fire',    type: 'game', category: 'battle-royale', icon: '🔥' },
  'creative_destruction.exe':           { name: 'Creative Destruction',type: 'game', category: 'battle-royale', icon: '🔨' },
  'rules_of_survival.exe':              { name: 'Rules of Survival',   type: 'game', category: 'battle-royale', icon: '📜' },
  'knives_out.exe':                     { name: 'Knives Out',          type: 'game', category: 'battle-royale', icon: '🔪' },
  'cyber_hunter.exe':                   { name: 'Cyber Hunter',        type: 'game', category: 'battle-royale', icon: '🤖' },
  'spellbreak.exe':                     { name: 'Spellbreak',          type: 'game', category: 'battle-royale', icon: '🔮' },
  'hyper_scape.exe':                    { name: 'Hyper Scape',         type: 'game', category: 'battle-royale', icon: '🏙️' },
  'realm_royale.exe':                   { name: 'Realm Royale',        type: 'game', category: 'battle-royale', icon: '🏰' },
  'the_culling.exe':                    { name: 'The Culling',         type: 'game', category: 'battle-royale', icon: '🪓' },
  'z1battle_royale.exe':                { name: 'Z1 Battle Royale',    type: 'game', category: 'battle-royale', icon: '⚡' },
  'h1z1.exe':                           { name: 'H1Z1',                type: 'game', category: 'battle-royale', icon: '🧟' },

  // ─── MOBA (new) ─────────────────────────────────────────────────────
  'mobilelegends.exe':                  { name: 'Mobile Legends',      type: 'game', category: 'moba',     icon: '🏆' },
  'arenaofvalor.exe':                   { name: 'Arena of Valor',      type: 'game', category: 'moba',     icon: '⚔️' },
  'pokemonunite.exe':                   { name: 'Pokemon UNITE',       type: 'game', category: 'moba',     icon: '⚡' },
  'battlerite.exe':                     { name: 'Battlerite',          type: 'game', category: 'moba',     icon: '🔥' },
  'gigantic.exe':                       { name: 'Gigantic',            type: 'game', category: 'moba',     icon: '🗿' },
  'paragon.exe':                        { name: 'Paragon',             type: 'game', category: 'moba',     icon: '🦸' },
  'infinitecrisis.exe':                 { name: 'Infinite Crisis',     type: 'game', category: 'moba',     icon: '🌌' },
  'dawngate.exe':                       { name: 'Dawngate',            type: 'game', category: 'moba',     icon: '🌅' },
  'strife.exe':                         { name: 'Strife',              type: 'game', category: 'moba',     icon: '⚔️' },
  'awesomenauts.exe':                   { name: 'Awesomenauts',        type: 'game', category: 'moba',     icon: '🚀' },
  'mondaynightcombat.exe':              { name: 'Monday Night Combat', type: 'game', category: 'moba',     icon: '🏈' },

  // ─── SANDBOX / OPEN WORLD (new) ─────────────────────────────────────
  'gta4.exe':                           { name: 'GTA IV',              type: 'game', category: 'sandbox',  icon: '🚗' },
  'gtavc.exe':                          { name: 'GTA Vice City',       type: 'game', category: 'sandbox',  icon: '🚗' },
  'gta3.exe':                           { name: 'GTA III',             type: 'game', category: 'sandbox',  icon: '🚗' },
  'reddeadredemption2.exe':             { name: 'Red Dead Redemption 2',type: 'game', category: 'sandbox', icon: '🤠' },
  'rdr2.exe':                           { name: 'RDR2',                type: 'game', category: 'sandbox',  icon: '🤠' },
  'reddeadredemption.exe':              { name: 'Red Dead Redemption', type: 'game', category: 'sandbox',  icon: '🤠' },
  'bully.exe':                          { name: 'Bully',               type: 'game', category: 'sandbox',  icon: '🎒' },
  'maxpayne3.exe':                      { name: 'Max Payne 3',         type: 'game', category: 'sandbox',  icon: '💊' },
  'maxpayne2.exe':                      { name: 'Max Payne 2',         type: 'game', category: 'sandbox',  icon: '💊' },
  'la_noire.exe':                       { name: 'L.A. Noire',          type: 'game', category: 'sandbox',  icon: '🕵️' },
  'manhunt.exe':                        { name: 'Manhunt',             type: 'game', category: 'sandbox',  icon: '🔪' },
  'manhunt2.exe':                       { name: 'Manhunt 2',           type: 'game', category: 'sandbox',  icon: '🔪' },
  'justcause4.exe':                     { name: 'Just Cause 4',        type: 'game', category: 'sandbox',  icon: '🪂' },
  'justcause3.exe':                     { name: 'Just Cause 3',        type: 'game', category: 'sandbox',  icon: '🪂' },
  'justcause2.exe':                     { name: 'Just Cause 2',        type: 'game', category: 'sandbox',  icon: '🪂' },
  'sleepingdogs.exe':                   { name: 'Sleeping Dogs',       type: 'game', category: 'sandbox',  icon: '🐕' },
  'saintsrow5.exe':                     { name: 'Saints Row (2022)',   type: 'game', category: 'sandbox',  icon: '😎' },
  'saintsrow4.exe':                     { name: 'Saints Row IV',       type: 'game', category: 'sandbox',  icon: '😎' },
  'saintsrowthethird.exe':              { name: 'Saints Row: The Third',type: 'game', category: 'sandbox', icon: '😎' },
  'watchdogs3.exe':                     { name: 'Watch Dogs: Legion',  type: 'game', category: 'sandbox',  icon: '🐕' },
  'watchdogs2.exe':                     { name: 'Watch Dogs 2',        type: 'game', category: 'sandbox',  icon: '🐕' },
  'watchdogs.exe':                      { name: 'Watch Dogs',          type: 'game', category: 'sandbox',  icon: '🐕' },
  'assassinscreedvalhalla.exe':         { name: "Assassin's Creed Valhalla",type: 'game', category: 'sandbox', icon: '🪓' },
  'assassinscreedodyssey.exe':          { name: "Assassin's Creed Odyssey",type: 'game', category: 'sandbox', icon: '🏛️' },
  'assassinscreedorigins.exe':          { name: "Assassin's Creed Origins",type: 'game', category: 'sandbox', icon: '🏺' },
  'assassinscreedsyndicate.exe':        { name: "Assassin's Creed Syndicate",type: 'game', category: 'sandbox', icon: '🎩' },
  'assassinscreedunity.exe':            { name: "Assassin's Creed Unity",type: 'game', category: 'sandbox', icon: '🗼' },
  'assassinscreedrogue.exe':            { name: "Assassin's Creed Rogue",type: 'game', category: 'sandbox', icon: '⛵' },
  'assassinscreed4.exe':                { name: "Assassin's Creed IV: Black Flag",type: 'game', category: 'sandbox', icon: '🏴‍☠️' },
  'assassinscreed3.exe':                { name: "Assassin's Creed III",type: 'game', category: 'sandbox', icon: '🦅' },
  'assassinscreedrevelations.exe':      { name: "Assassin's Creed: Revelations",type: 'game', category: 'sandbox', icon: '🕌' },
  'assassinscreedbrotherhood.exe':      { name: "Assassin's Creed: Brotherhood",type: 'game', category: 'sandbox', icon: '🏰' },
  'assassinscreed2.exe':                { name: "Assassin's Creed II",type: 'game', category: 'sandbox', icon: '🎭' },
  'farcry5.exe':                        { name: 'Far Cry 5',           type: 'game', category: 'sandbox',  icon: '🌄' },
  'farcry4.exe':                        { name: 'Far Cry 4',           type: 'game', category: 'sandbox',  icon: '🏔️' },
  'farcry3.exe':                        { name: 'Far Cry 3',           type: 'game', category: 'sandbox',  icon: '🏝️' },
  'farcry2.exe':                        { name: 'Far Cry 2',           type: 'game', category: 'sandbox',  icon: '🌍' },
  'farcry.exe':                         { name: 'Far Cry',             type: 'game', category: 'sandbox',  icon: '🌍' },
  'farcrynewdawn.exe':                  { name: 'Far Cry New Dawn',    type: 'game', category: 'sandbox',  icon: '🌅' },
  'farcryprimal.exe':                   { name: 'Far Cry Primal',      type: 'game', category: 'sandbox',  icon: '🦣' },
  'dyinglight2.exe':                    { name: 'Dying Light 2',       type: 'game', category: 'sandbox',  icon: '🧟' },
  'dyinglight.exe':                     { name: 'Dying Light',         type: 'game', category: 'sandbox',  icon: '🧟' },
  'deadisland2.exe':                    { name: 'Dead Island 2',       type: 'game', category: 'sandbox',  icon: '🏝️' },
  'deadisland.exe':                     { name: 'Dead Island',         type: 'game', category: 'sandbox',  icon: '🏝️' },
  'mafiadefinitiveedition.exe':         { name: 'Mafia: Definitive Edition',type: 'game', category: 'sandbox', icon: '🎩' },
  'mafia3.exe':                         { name: 'Mafia III',           type: 'game', category: 'sandbox',  icon: '🚗' },
  'mafia2.exe':                         { name: 'Mafia II',            type: 'game', category: 'sandbox',  icon: '🚗' },
  'mafia.exe':                          { name: 'Mafia',               type: 'game', category: 'sandbox',  icon: '🚗' },
  'madmax.exe':                         { name: 'Mad Max',             type: 'game', category: 'sandbox',  icon: '🚗' },
  'shadowofmordor.exe':                 { name: 'Shadow of Mordor',    type: 'game', category: 'sandbox',  icon: '👁️' },
  'shadowofwar.exe':                    { name: 'Shadow of War',       type: 'game', category: 'sandbox',  icon: '👁️' },
  'arkhamknight.exe':                   { name: 'Batman: Arkham Knight',type: 'game', category: 'sandbox', icon: '🦇' },
  'arkhamcity.exe':                     { name: 'Batman: Arkham City', type: 'game', category: 'sandbox',  icon: '🦇' },
  'arkhamasylum.exe':                   { name: 'Batman: Arkham Asylum',type: 'game', category: 'sandbox', icon: '🦇' },
  'arkhamorigins.exe':                  { name: 'Batman: Arkham Origins',type: 'game', category: 'sandbox', icon: '🦇' },
  'legostarwars.exe':                   { name: 'LEGO Star Wars',      type: 'game', category: 'sandbox',  icon: '🧱' },
  'legoharrypotter.exe':                { name: 'LEGO Harry Potter',   type: 'game', category: 'sandbox',  icon: '⚡' },
  'legomarvel.exe':                     { name: 'LEGO Marvel Super Heroes',type: 'game', category: 'sandbox', icon: '🦸' },
  'prototype2.exe':                     { name: 'Prototype 2',         type: 'game', category: 'sandbox',  icon: '🦠' },
  'prototype.exe':                      { name: 'Prototype',           type: 'game', category: 'sandbox',  icon: '🦠' },

  // ─── RPG / MMO (new) ────────────────────────────────────────────────
  'nierautomata.exe':                   { name: 'NieR: Automata',      type: 'game', category: 'rpg',      icon: '🤖' },
  'nierrequiem.exe':                    { name: 'NieR Replicant',      type: 'game', category: 'rpg',      icon: '🤖' },
  'finalfantasy7remake.exe':            { name: 'Final Fantasy VII Remake',type: 'game', category: 'rpg',   icon: '⚔️' },
  'ff7remake.exe':                      { name: 'Final Fantasy VII Remake',type: 'game', category: 'rpg',   icon: '⚔️' },
  'finalfantasyxvi.exe':                { name: 'Final Fantasy XVI',   type: 'game', category: 'rpg',      icon: '🐉' },
  'finalfantasyxv.exe':                 { name: 'Final Fantasy XV',    type: 'game', category: 'rpg',      icon: '🚗' },
  'finalfantasyxiii.exe':                { name: 'Final Fantasy XIII',  type: 'game', category: 'rpg',      icon: '⚔️' },
  'finalfantasyxii.exe':                { name: 'Final Fantasy XII',   type: 'game', category: 'rpg',      icon: '⚔️' },
  'finalfantasyx.exe':                  { name: 'Final Fantasy X',     type: 'game', category: 'rpg',      icon: '⚔️' },
  'finalfantasyix.exe':                 { name: 'Final Fantasy IX',    type: 'game', category: 'rpg',      icon: '⚔️' },
  'dragonquestxi.exe':                  { name: 'Dragon Quest XI',     type: 'game', category: 'rpg',      icon: '🐉' },
  'dragonquestx.exe':                   { name: 'Dragon Quest X',      type: 'game', category: 'mmo',      icon: '🐉' },
  'octopathtraveler.exe':               { name: 'Octopath Traveler',   type: 'game', category: 'rpg',      icon: '🗺️' },
  'octopathtraveler2.exe':              { name: 'Octopath Traveler II',type: 'game', category: 'rpg',      icon: '🗺️' },
  'bravelydefault2.exe':                { name: 'Bravely Default II',  type: 'game', category: 'rpg',      icon: '⚔️' },
  'trianglestrategy.exe':               { name: 'Triangle Strategy',   type: 'game', category: 'rpg',      icon: '🔺' },
  'chrono_trigger.exe':                 { name: 'Chrono Trigger',      type: 'game', category: 'rpg',      icon: '⏰' },
  'chrono_cross.exe':                   { name: 'Chrono Cross',        type: 'game', category: 'rpg',      icon: '⏰' },
  'xenoblade3.exe':                     { name: 'Xenoblade Chronicles 3',type: 'game', category: 'rpg',   icon: '⚔️' },
  'xenoblade2.exe':                     { name: 'Xenoblade Chronicles 2',type: 'game', category: 'rpg',   icon: '⚔️' },
  'xenoblade.exe':                      { name: 'Xenoblade Chronicles',type: 'game', category: 'rpg',      icon: '⚔️' },
  'persona5royal.exe':                  { name: 'Persona 5 Royal',     type: 'game', category: 'rpg',      icon: '🎭' },
  'persona5.exe':                       { name: 'Persona 5',           type: 'game', category: 'rpg',      icon: '🎭' },
  'persona4golden.exe':                 { name: 'Persona 4 Golden',    type: 'game', category: 'rpg',      icon: '🎭' },
  'persona4.exe':                       { name: 'Persona 4',           type: 'game', category: 'rpg',      icon: '🎭' },
  'persona3reload.exe':                 { name: 'Persona 3 Reload',    type: 'game', category: 'rpg',      icon: '🎭' },
  'persona3.exe':                       { name: 'Persona 3',           type: 'game', category: 'rpg',      icon: '🎭' },
  'shinmegamitenseiv.exe':              { name: 'Shin Megami Tensei V',type: 'game', category: 'rpg',      icon: '😈' },
  'smtv.exe':                           { name: 'Shin Megami Tensei V',type: 'game', category: 'rpg',      icon: '😈' },
  'soulsborne.exe':                     { name: 'Soulsborne',          type: 'game', category: 'rpg',      icon: '💀' },
  'demonsouls.exe':                     { name: "Demon's Souls",       type: 'game', category: 'rpg',      icon: '💀' },
  'armoredcore6.exe':                   { name: 'Armored Core VI',     type: 'game', category: 'rpg',      icon: '🤖' },
  'armoredcorevi.exe':                  { name: 'Armored Core VI',     type: 'game', category: 'rpg',      icon: '🤖' },
  'kingdomhearts3.exe':                 { name: 'Kingdom Hearts III',  type: 'game', category: 'rpg',      icon: '👑' },
  'kingdomhearts2.exe':                 { name: 'Kingdom Hearts II',   type: 'game', category: 'rpg',      icon: '👑' },
  'kingdomhearts.exe':                  { name: 'Kingdom Hearts',      type: 'game', category: 'rpg',      icon: '👑' },
  'nioh2.exe':                          { name: 'Nioh 2',              type: 'game', category: 'rpg',      icon: '⚔️' },
  'nioh.exe':                           { name: 'Nioh',                type: 'game', category: 'rpg',      icon: '⚔️' },
  'wo_long.exe':                        { name: 'Wo Long: Fallen Dynasty',type: 'game', category: 'rpg',   icon: '🐉' },
  'liesofp.exe':                        { name: 'Lies of P',           type: 'game', category: 'rpg',      icon: '🎭' },
  'starwarsjedifallenorder.exe':        { name: 'Star Wars Jedi: Fallen Order',type: 'game', category: 'rpg', icon: '⚔️' },
  'starwarsjedi.exe':                   { name: 'Star Wars Jedi: Survivor',type: 'game', category: 'rpg',  icon: '⚔️' },
  'mass_effect_legendary.exe':          { name: 'Mass Effect Legendary',type: 'game', category: 'rpg',   icon: '🚀' },
  'masseffect2.exe':                    { name: 'Mass Effect 2',       type: 'game', category: 'rpg',      icon: '🚀' },
  'masseffect3.exe':                    { name: 'Mass Effect 3',       type: 'game', category: 'rpg',      icon: '🚀' },
  'masseffectandromeda.exe':            { name: 'Mass Effect: Andromeda',type: 'game', category: 'rpg',  icon: '🚀' },
  'dragonsdogma2.exe':                  { name: "Dragon's Dogma 2",    type: 'game', category: 'rpg',      icon: '🐉' },
  'dragonsdogma.exe':                   { name: "Dragon's Dogma",      type: 'game', category: 'rpg',      icon: '🐉' },
  'divinityoriginalsin2.exe':           { name: 'Divinity: Original Sin 2',type: 'game', category: 'rpg', icon: '⚔️' },
  'divinityoriginalsin.exe':            { name: 'Divinity: Original Sin',type: 'game', category: 'rpg',  icon: '⚔️' },
  'baldursgate3.exe':                   { name: "Baldur's Gate 3",     type: 'game', category: 'rpg',      icon: '⚔️' },
  'bg3.exe':                            { name: "Baldur's Gate 3",     type: 'game', category: 'rpg',      icon: '⚔️' },
  'baldursgate2.exe':                   { name: "Baldur's Gate II",    type: 'game', category: 'rpg',      icon: '⚔️' },
  'baldursgate.exe':                    { name: "Baldur's Gate",       type: 'game', category: 'rpg',      icon: '⚔️' },
  'icewinddale.exe':                    { name: 'Icewind Dale',        type: 'game', category: 'rpg',      icon: '❄️' },
  'planescapetorment.exe':              { name: 'Planescape: Torment', type: 'game', category: 'rpg',      icon: '🌀' },
  'neverwinter.exe':                    { name: 'Neverwinter',         type: 'game', category: 'mmo',      icon: '🏰' },
  'nwmain.exe':                         { name: 'Neverwinter Nights',  type: 'game', category: 'rpg',      icon: '🌙' },
  'tormenttidesofnumenera.exe':         { name: 'Torment: Tides of Numenera',type: 'game', category: 'rpg', icon: '🌀' },
  'wasteland3.exe':                     { name: 'Wasteland 3',         type: 'game', category: 'rpg',      icon: '☢️' },
  'wasteland2.exe':                     { name: 'Wasteland 2',         type: 'game', category: 'rpg',      icon: '☢️' },
  'pillarsofeternity2.exe':             { name: 'Pillars of Eternity II',type: 'game', category: 'rpg',  icon: '🏛️' },
  'pillarsofeternity.exe':              { name: 'Pillars of Eternity',  type: 'game', category: 'rpg',      icon: '🏛️' },
  'tyranny.exe':                        { name: 'Tyranny',             type: 'game', category: 'rpg',      icon: '⚖️' },
  'outward.exe':                        { name: 'Outward',             type: 'game', category: 'rpg',      icon: '🧭' },
  'greedfall.exe':                      { name: 'Greedfall',           type: 'game', category: 'rpg',      icon: '🏝️' },
  'vampyr.exe':                         { name: 'Vampyr',              type: 'game', category: 'rpg',      icon: '🧛' },
  'aplaguetaleinnocence.exe':          { name: 'A Plague Tale: Innocence',type: 'game', category: 'rpg', icon: '🐀' },
  'aplaguetalerequiem.exe':           { name: 'A Plague Tale: Requiem',type: 'game', category: 'rpg',  icon: '🐀' },
  'remnant2.exe':                       { name: 'Remnant 2',           type: 'game', category: 'rpg',      icon: '🔥' },
  'remnantfromtheashes.exe':           { name: 'Remnant: From the Ashes',type: 'game', category: 'rpg', icon: '🔥' },
  'outriders.exe':                      { name: 'Outriders',           type: 'game', category: 'rpg',      icon: '🌍' },
  'godfall.exe':                        { name: 'Godfall',             type: 'game', category: 'rpg',      icon: '👑' },
  'blessunleashed.exe':                { name: 'Bless Unleashed',     type: 'game', category: 'mmo',      icon: '⚔️' },
  'crowfall.exe':                       { name: 'Crowfall',            type: 'game', category: 'mmo',      icon: '🦅' },
  'camelotunchained.exe':               { name: 'Camelot Unchained',    type: 'game', category: 'mmo',      icon: '🏰' },
  'lifeisfeudalmmo.exe':                { name: 'Life is Feudal: MMO',  type: 'game', category: 'mmo',      icon: '🏰' },
  'repopulation.exe':                  { name: 'The Repopulation',     type: 'game', category: 'mmo',      icon: '🌍' },
  'starwarsgalaxies.exe':               { name: 'Star Wars Galaxies',  type: 'game', category: 'mmo',      icon: '⭐' },
  'starwarsoldrepublic.exe':           { name: 'Star Wars: The Old Republic',type: 'game', category: 'mmo', icon: '⚔️' },
  'swtor.exe':                          { name: 'Star Wars: The Old Republic',type: 'game', category: 'mmo', icon: '⚔️' },
  'destiny2.exe':                       { name: 'Destiny 2',           type: 'game', category: 'mmo',      icon: '⭐' },
  'destiny.exe':                        { name: 'Destiny',             type: 'game', category: 'mmo',      icon: '⭐' },
  'warframe.exe':                      { name: 'Warframe',            type: 'game', category: 'mmo',      icon: '🤖' },

  // ─── RACING (new) ────────────────────────────────────────────────────
  'thecrew2.exe':                       { name: 'The Crew 2',          type: 'game', category: 'racing',   icon: '🚗' },
  'thecrew.exe':                        { name: 'The Crew',            type: 'game', category: 'racing',   icon: '🚗' },
  'thecrewmotorfest.exe':               { name: 'The Crew Motorfest',  type: 'game', category: 'racing',   icon: '🚗' },
  'forzahorizon4.exe':                  { name: 'Forza Horizon 4',     type: 'game', category: 'racing',   icon: '🚗' },
  'forzahorizon3.exe':                  { name: 'Forza Horizon 3',     type: 'game', category: 'racing',   icon: '🚗' },
  'forzahorizon2.exe':                  { name: 'Forza Horizon 2',     type: 'game', category: 'racing',   icon: '🚗' },
  'forzamotorsport7.exe':               { name: 'Forza Motorsport 7',  type: 'game', category: 'racing',   icon: '🏎️' },
  'forzamotorsport6.exe':               { name: 'Forza Motorsport 6',  type: 'game', category: 'racing',   icon: '🏎️' },
  'f12022.exe':                        { name: 'F1 2022',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12021.exe':                        { name: 'F1 2021',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12020.exe':                        { name: 'F1 2020',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12019.exe':                        { name: 'F1 2019',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12018.exe':                        { name: 'F1 2018',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12017.exe':                        { name: 'F1 2017',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12016.exe':                        { name: 'F1 2016',             type: 'game', category: 'racing',   icon: '🏎️' },
  'projectcars2.exe':                   { name: 'Project CARS 2',      type: 'game', category: 'racing',   icon: '🏎️' },
  'projectcars.exe':                    { name: 'Project CARS',        type: 'game', category: 'racing',   icon: '🏎️' },
  'projectcars3.exe':                   { name: 'Project CARS 3',      type: 'game', category: 'racing',   icon: '🏎️' },
  'gridlegends.exe':                    { name: 'GRID Legends',        type: 'game', category: 'racing',   icon: '🏎️' },
  'gridautosport.exe':                 { name: 'GRID Autosport',      type: 'game', category: 'racing',   icon: '🏎️' },
  'grid2.exe':                         { name: 'GRID 2',              type: 'game', category: 'racing',   icon: '🏎️' },
  'grid.exe':                          { name: 'GRID',                type: 'game', category: 'racing',   icon: '🏎️' },
  'dirt5.exe':                         { name: 'DiRT 5',              type: 'game', category: 'racing',   icon: '🚗' },
  'dirt4.exe':                         { name: 'DiRT 4',              type: 'game', category: 'racing',   icon: '🚗' },
  'dirtrally2.exe':                    { name: 'DiRT Rally 2',        type: 'game', category: 'racing',   icon: '🚗' },
  'dirtrally.exe':                     { name: 'DiRT Rally',          type: 'game', category: 'racing',   icon: '🚗' },
  'dirt3.exe':                         { name: 'DiRT 3',              type: 'game', category: 'racing',   icon: '🚗' },
  'dirt2.exe':                         { name: 'DiRT 2',              type: 'game', category: 'racing',   icon: '🚗' },
  'dirt.exe':                          { name: 'DiRT',                type: 'game', category: 'racing',   icon: '🚗' },
  'needforspeedunbound.exe':            { name: 'Need for Speed: Unbound',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedheat.exe':              { name: 'Need for Speed: Heat',type: 'game', category: 'racing',   icon: '🔥' },
  'needforspeedpayback.exe':            { name: 'Need for Speed: Payback',type: 'game', category: 'racing', icon: '💰' },
  'needforspeed2015.exe':              { name: 'Need for Speed (2015)',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedrivals.exe':             { name: 'Need for Speed: Rivals',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedmostwanted2.exe':        { name: 'Need for Speed: Most Wanted (2012)',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedmostwanted.exe':        { name: 'Need for Speed: Most Wanted',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedundercover.exe':        { name: 'Need for Speed: Undercover',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedprostreet.exe':         { name: 'Need for Speed: ProStreet',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedcarbon.exe':            { name: 'Need for Speed: Carbon',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedmostwanted2005.exe':    { name: 'Need for Speed: Most Wanted (2005)',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedunderground2.exe':      { name: 'Need for Speed: Underground 2',type: 'game', category: 'racing', icon: '🚗' },
  'needforspeedunderground.exe':       { name: 'Need for Speed: Underground',type: 'game', category: 'racing', icon: '🚗' },
  'testdriveunlimited2.exe':           { name: 'Test Drive Unlimited 2',type: 'game', category: 'racing', icon: '🚗' },
  'testdriveunlimited.exe':            { name: 'Test Drive Unlimited',type: 'game', category: 'racing', icon: '🚗' },
  'midnightclubla.exe':                { name: 'Midnight Club: LA',    type: 'game', category: 'racing',   icon: '🌃' },
  'midnightclub3.exe':                 { name: 'Midnight Club 3',      type: 'game', category: 'racing',   icon: '🌃' },
  'burnoutparadise.exe':              { name: 'Burnout Paradise',     type: 'game', category: 'racing',   icon: '🔥' },
  'burnoutrevenge.exe':               { name: 'Burnout Revenge',      type: 'game', category: 'racing',   icon: '🔥' },
  'burnout3takedown.exe':             { name: 'Burnout 3: Takedown',  type: 'game', category: 'racing',   icon: '🔥' },
  'splitsecond.exe':                  { name: 'Split/Second',         type: 'game', category: 'racing',   icon: '💥' },
  'blur.exe':                          { name: 'Blur',                type: 'game', category: 'racing',   icon: '💨' },
  'mariokart8deluxe.exe':             { name: 'Mario Kart 8 Deluxe',  type: 'game', category: 'racing',   icon: '🏎️' },
  'mariokart8.exe':                   { name: 'Mario Kart 8',         type: 'game', category: 'racing',   icon: '🏎️' },
  'crashteamracing.exe':              { name: 'Crash Team Racing',    type: 'game', category: 'racing',   icon: '🏎️' },
  'modnationracers.exe':              { name: 'ModNation Racers',     type: 'game', category: 'racing',   icon: '🏎️' },
  'littlebigplanetkarting.exe':       { name: 'LittleBigPlanet Karting',type: 'game', category: 'racing', icon: '🏎️' },
  'sonicallstarsracing.exe':          { name: 'Sonic & All-Stars Racing',type: 'game', category: 'racing', icon: '🏎️' },
  'sonicracing.exe':                 { name: 'Team Sonic Racing',    type: 'game', category: 'racing',   icon: '🏎️' },
  'beachbumracer.exe':               { name: 'Beach Buggy Racing',   type: 'game', category: 'racing',   icon: '🏖️' },
  'beachbumracing2.exe':             { name: 'Beach Buggy Racing 2',  type: 'game', category: 'racing',   icon: '🏖️' },
  'hillclimbracing2.exe':             { name: 'Hill Climb Racing 2',   type: 'game', category: 'racing',   icon: '🏔️' },
  'hillclimbracing.exe':              { name: 'Hill Climb Racing',     type: 'game', category: 'racing',   icon: '🏔️' },
  'asphalt9legends.exe':              { name: 'Asphalt 9: Legends',   type: 'game', category: 'racing',   icon: '🏎️' },
  'asphalt8airborne.exe':             { name: 'Asphalt 8: Airborne',   type: 'game', category: 'racing',   icon: '✈️' },
  'asphalt7heat.exe':                 { name: 'Asphalt 7: Heat',      type: 'game', category: 'racing',   icon: '🔥' },
  'realracing3.exe':                  { name: 'Real Racing 3',        type: 'game', category: 'racing',   icon: '🏎️' },
  'gearclub.exe':                     { name: 'Gear.Club',            type: 'game', category: 'racing',   icon: '⚙️' },
  'gearclubunlimited.exe':            { name: 'Gear.Club Unlimited',  type: 'game', category: 'racing',   icon: '⚙️' },
  'gtsport.exe':                      { name: 'Gran Turismo Sport',   type: 'game', category: 'racing',   icon: '🏎️' },
  'gran turismo sport.exe':           { name: 'Gran Turismo Sport',   type: 'game', category: 'racing',   icon: '🏎️' },
  'gran turismo 7.exe':               { name: 'Gran Turismo 7',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gt7.exe':                          { name: 'Gran Turismo 7',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gran turismo 6.exe':               { name: 'Gran Turismo 6',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gt6.exe':                          { name: 'Gran Turismo 6',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gran turismo 5.exe':               { name: 'Gran Turismo 5',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gt5.exe':                          { name: 'Gran Turismo 5',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gran turismo 4.exe':               { name: 'Gran Turismo 4',       type: 'game', category: 'racing',   icon: '🏎️' },
  'gt4.exe':                          { name: 'Gran Turismo 4',       type: 'game', category: 'racing',   icon: '🏎️' },
  'wanganmidnightmaximumtune.exe':    { name: 'Wangan Midnight Maximum Tune',type: 'game', category: 'racing', icon: '🚗' },
  'initiald.exe':                     { name: 'Initial D',            type: 'game', category: 'racing',   icon: '🚗' },

  // ─── RHYTHM / MUSIC (new) ─────────────────────────────────────────────
  'taiko no tatsujin.exe':            { name: 'Taiko no Tatsujin',     type: 'game', category: 'rhythm',   icon: '🥁' },
  'taiko.exe':                        { name: 'Taiko no Tatsujin',     type: 'game', category: 'rhythm',   icon: '🥁' },
  'osu.exe':                          { name: 'osu!',                type: 'game', category: 'rhythm',   icon: '🎯' },
  'clonehero.exe':                    { name: 'Clone Hero',           type: 'game', category: 'rhythm',   icon: '🎸' },
  'guitarhero3.exe':                  { name: 'Guitar Hero III',      type: 'game', category: 'rhythm',   icon: '🎸' },
  'guitarhero2.exe':                  { name: 'Guitar Hero II',       type: 'game', category: 'rhythm',   icon: '🎸' },
  'guitarhero.exe':                   { name: 'Guitar Hero',          type: 'game', category: 'rhythm',   icon: '🎸' },
  'rockband2.exe':                    { name: 'Rock Band 2',          type: 'game', category: 'rhythm',   icon: '🎸' },
  'rockband.exe':                     { name: 'Rock Band',            type: 'game', category: 'rhythm',   icon: '🎸' },
  'rockband3.exe':                    { name: 'Rock Band 3',          type: 'game', category: 'rhythm',   icon: '🎸' },
  'rockband4.exe':                    { name: 'Rock Band 4',          type: 'game', category: 'rhythm',   icon: '🎸' },
  'rocksmith.exe':                    { name: 'Rocksmith',            type: 'game', category: 'rhythm',   icon: '🎸' },
  'rocksmith2014.exe':                { name: 'Rocksmith 2014',       type: 'game', category: 'rhythm',   icon: '🎸' },
  'cymatics.exe':                    { name: 'Cymatics',             type: 'game', category: 'rhythm',   icon: '🎵' },
  'audica.exe':                       { name: 'Audica',              type: 'game', category: 'rhythm',   icon: '🎵' },
  'beat saber.exe':                  { name: 'Beat Saber',           type: 'game', category: 'rhythm',   icon: '⚔️' },
  'beatsaber.exe':                   { name: 'Beat Saber',           type: 'game', category: 'rhythm',   icon: '⚔️' },
  'synthriders.exe':                  { name: 'Synth Riders',         type: 'game', category: 'rhythm',   icon: '🎵' },
  'pistol whip.exe':                 { name: 'Pistol Whip',          type: 'game', category: 'rhythm',   icon: '🔫' },
  'ragnarock.exe':                    { name: 'Ragnarock',            type: 'game', category: 'rhythm',   icon: '🪨' },
  'guitar hero live.exe':            { name: 'Guitar Hero Live',     type: 'game', category: 'rhythm',   icon: '🎸' },
  'just dance 2024.exe':             { name: 'Just Dance 2024',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2023.exe':             { name: 'Just Dance 2023',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2022.exe':             { name: 'Just Dance 2022',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2021.exe':             { name: 'Just Dance 2021',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2020.exe':             { name: 'Just Dance 2020',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2019.exe':             { name: 'Just Dance 2019',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2018.exe':             { name: 'Just Dance 2018',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2017.exe':             { name: 'Just Dance 2017',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2016.exe':             { name: 'Just Dance 2016',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2015.exe':             { name: 'Just Dance 2015',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance 2014.exe':             { name: 'Just Dance 2014',      type: 'game', category: 'rhythm',   icon: '💃' },
  'just dance.exe':                  { name: 'Just Dance',           type: 'game', category: 'rhythm',   icon: '💃' },
  'dance dance revolution.exe':      { name: 'Dance Dance Revolution',type: 'game', category: 'rhythm', icon: '💃' },
  'ddr.exe':                          { name: 'Dance Dance Revolution',type: 'game', category: 'rhythm', icon: '💃' },
  'stepmania.exe':                    { name: 'StepMania',            type: 'game', category: 'rhythm',   icon: '💃' },
  'crypt of the necrodancer.exe':     { name: 'Crypt of the NecroDancer',type: 'game', category: 'rhythm', icon: '💀' },
  'cadence of hyrule.exe':           { name: 'Cadence of Hyrule',     type: 'game', category: 'rhythm',   icon: '🎵' },
  'rhythm doctor.exe':               { name: 'Rhythm Doctor',        type: 'game', category: 'rhythm',   icon: '❤️' },
  'rhythm heaven.exe':               { name: 'Rhythm Heaven',        type: 'game', category: 'rhythm',   icon: '🎵' },
  'muse dash.exe':                   { name: 'Muse Dash',            type: 'game', category: 'rhythm',   icon: '🐱' },
  'deemo.exe':                        { name: 'Deemo',               type: 'game', category: 'rhythm',   icon: '🎹' },
  'voez.exe':                         { name: 'VOEZ',                type: 'game', category: 'rhythm',   icon: '🎵' },
  'lanota.exe':                      { name: 'Lanota',              type: 'game', category: 'rhythm',   icon: '🎵' },
  'cytus.exe':                       { name: 'Cytus',               type: 'game', category: 'rhythm',   icon: '🎵' },
  'cytus ii.exe':                    { name: 'Cytus II',            type: 'game', category: 'rhythm',   icon: '🎵' },
  'overrhythm.exe':                  { name: 'OverRhythm',           type: 'game', category: 'rhythm',   icon: '🎵' },
  'phigros.exe':                     { name: 'Phigros',              type: 'game', category: 'rhythm',   icon: '🎵' },
  'arcaea.exe':                      { name: 'Arcaea',              type: 'game', category: 'rhythm',   icon: '🎵' },
  'dynamix.exe':                     { name: 'Dynamix',              type: 'game', category: 'rhythm',   icon: '🎵' },
  'pianista.exe':                    { name: 'Pianista',             type: 'game', category: 'rhythm',   icon: '🎹' },
  'd4dj.exe':                        { name: 'D4DJ',                type: 'game', category: 'rhythm',   icon: '🎵' },
  'project sekai.exe':              { name: 'Project Sekai',        type: 'game', category: 'rhythm',   icon: '🎵' },
  'idolmaster.exe':                  { name: 'THE IDOLM@STER',       type: 'game', category: 'rhythm',   icon: '🎤' },
  'love live.exe':                   { name: 'Love Live!',           type: 'game', category: 'rhythm',   icon: '🎤' },
  'bang dream.exe':                  { name: 'BanG Dream!',          type: 'game', category: 'rhythm',   icon: '🎸' },
  'show by rock.exe':                { name: 'Show By Rock!!',       type: 'game', category: 'rhythm',   icon: '🎸' },
  'utapri.exe':                      { name: 'Uta no Prince-sama',    type: 'game', category: 'rhythm',   icon: '🎤' },
  'enstars.exe':                     { name: 'Ensemble Stars!',      type: 'game', category: 'rhythm',   icon: '⭐' },
  'hypmic.exe':                      { name: 'Hypnosis Mic',        type: 'game', category: 'rhythm',   icon: '🎤' },

  // ─── SIMULATION (new) ─────────────────────────────────────────────────
  'paralives.exe':                   { name: 'Paralives',            type: 'game', category: 'sim',      icon: '🏠' },
  'life by you.exe':                 { name: 'Life by You',          type: 'game', category: 'sim',      icon: '🏠' },
  'the sims 5.exe':                  { name: 'The Sims 5',           type: 'game', category: 'sim',      icon: '🏠' },
  'thesims5.exe':                    { name: 'The Sims 5',           type: 'game', category: 'sim',      icon: '🏠' },
  'project rene.exe':                { name: 'Project Rene',         type: 'game', category: 'sim',      icon: '🏠' },
  'cities skylines 2.exe':           { name: 'Cities: Skylines II', type: 'game', category: 'sim',      icon: '🏙️' },
  'citiesskylines2.exe':             { name: 'Cities: Skylines II', type: 'game', category: 'sim',      icon: '🏙️' },
  'skylines 2.exe':                  { name: 'Cities: Skylines II', type: 'game', category: 'sim',      icon: '🏙️' },
  'simcity 2013.exe':                { name: 'SimCity (2013)',       type: 'game', category: 'sim',      icon: '🏙️' },
  'simcity2013.exe':                 { name: 'SimCity (2013)',       type: 'game', category: 'sim',      icon: '🏙️' },
  'simcity.exe':                     { name: 'SimCity',              type: 'game', category: 'sim',      icon: '🏙️' },
  'simcity4.exe':                    { name: 'SimCity 4',            type: 'game', category: 'sim',      icon: '🏙️' },
  'simcity societies.exe':           { name: 'SimCity Societies',    type: 'game', category: 'sim',      icon: '🏙️' },
  'cities xl 2012.exe':              { name: 'Cities XL 2012',       type: 'game', category: 'sim',      icon: '🏙️' },
  'cities xl platinum.exe':           { name: 'Cities XL Platinum',   type: 'game', category: 'sim',      icon: '🏙️' },
  'cities xl.exe':                   { name: 'Cities XL',            type: 'game', category: 'sim',      icon: '🏙️' },
  'xl nations.exe':                  { name: 'XL Nations',           type: 'game', category: 'sim',      icon: '🏙️' },
  'tropico 6.exe':                   { name: 'Tropico 6',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico6.exe':                     { name: 'Tropico 6',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico 5.exe':                   { name: 'Tropico 5',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico5.exe':                     { name: 'Tropico 5',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico 4.exe':                   { name: 'Tropico 4',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico4.exe':                     { name: 'Tropico 4',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico 3.exe':                   { name: 'Tropico 3',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico3.exe':                     { name: 'Tropico 3',            type: 'game', category: 'sim',      icon: '🏝️' },
  'tropico.exe':                     { name: 'Tropico',              type: 'game', category: 'sim',      icon: '🏝️' },
  'anno 1800.exe':                   { name: 'Anno 1800',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno1800.exe':                    { name: 'Anno 1800',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno 2205.exe':                   { name: 'Anno 2205',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno2205.exe':                    { name: 'Anno 2205',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno 2070.exe':                   { name: 'Anno 2070',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno2070.exe':                    { name: 'Anno 2070',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno 1404.exe':                   { name: 'Anno 1404',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno1404.exe':                    { name: 'Anno 1404',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno 1404 history edition.exe':   { name: 'Anno 1404 History Edition',type: 'game', category: 'sim', icon: '⛵' },
  'anno 1701.exe':                   { name: 'Anno 1701',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno1701.exe':                    { name: 'Anno 1701',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno 1503.exe':                   { name: 'Anno 1503',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno1503.exe':                    { name: 'Anno 1503',            type: 'game', category: 'sim',      icon: '⛵' },
  'anno.exe':                        { name: 'Anno',                type: 'game', category: 'sim',      icon: '⛵' },
  'settlements 2.exe':               { name: 'The Settlers II',      type: 'game', category: 'sim',      icon: '🏰' },
  'thesettlers2.exe':                { name: 'The Settlers II',      type: 'game', category: 'sim',      icon: '🏰' },
  'settlements 3.exe':               { name: 'The Settlers III',     type: 'game', category: 'sim',      icon: '🏰' },
  'thesettlers3.exe':                { name: 'The Settlers III',     type: 'game', category: 'sim',      icon: '🏰' },
  'settlements 4.exe':               { name: 'The Settlers IV',      type: 'game', category: 'sim',      icon: '🏰' },
  'thesettlers4.exe':                { name: 'The Settlers IV',      type: 'game', category: 'sim',      icon: '🏰' },
  'settlements 7.exe':               { name: 'The Settlers VII',     type: 'game', category: 'sim',      icon: '🏰' },
  'thesettlers7.exe':                { name: 'The Settlers VII',     type: 'game', category: 'sim',      icon: '🏰' },
  'settlements.exe':                 { name: 'The Settlers',         type: 'game', category: 'sim',      icon: '🏰' },
  'thesettlers.exe':                 { name: 'The Settlers',         type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold crusader 2.exe':       { name: 'Stronghold Crusader 2',type: 'game', category: 'sim',      icon: '🏰' },
  'strongholdcrusader2.exe':         { name: 'Stronghold Crusader 2',type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold crusader.exe':         { name: 'Stronghold Crusader',  type: 'game', category: 'sim',      icon: '🏰' },
  'strongholdcrusader.exe':          { name: 'Stronghold Crusader',  type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold 3.exe':                { name: 'Stronghold 3',         type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold3.exe':                 { name: 'Stronghold 3',         type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold 2.exe':                { name: 'Stronghold 2',         type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold2.exe':                 { name: 'Stronghold 2',         type: 'game', category: 'sim',      icon: '🏰' },
  'stronghold.exe':                  { name: 'Stronghold',           type: 'game', category: 'sim',      icon: '🏰' },
  'farming simulator 22.exe':        { name: 'Farming Simulator 22', type: 'game', category: 'sim',      icon: '🚜' },
  'farmingsimulator22.exe':          { name: 'Farming Simulator 22', type: 'game', category: 'sim',      icon: '🚜' },
  'farming simulator 19.exe':        { name: 'Farming Simulator 19', type: 'game', category: 'sim',      icon: '🚜' },
  'farmingsimulator19.exe':          { name: 'Farming Simulator 19', type: 'game', category: 'sim',      icon: '🚜' },
  'farming simulator 17.exe':        { name: 'Farming Simulator 17', type: 'game', category: 'sim',      icon: '🚜' },
  'farmingsimulator17.exe':          { name: 'Farming Simulator 17', type: 'game', category: 'sim',      icon: '🚜' },
  'farming simulator 15.exe':        { name: 'Farming Simulator 15', type: 'game', category: 'sim',      icon: '🚜' },
  'farmingsimulator15.exe':          { name: 'Farming Simulator 15', type: 'game', category: 'sim',      icon: '🚜' },
  'euro truck simulator 2.exe':     { name: 'Euro Truck Simulator 2',type: 'game', category: 'sim',      icon: '🚛' },
  'eurotrucksimulator2.exe':        { name: 'Euro Truck Simulator 2',type: 'game', category: 'sim',      icon: '🚛' },
  'american truck simulator.exe':    { name: 'American Truck Simulator',type: 'game', category: 'sim',  icon: '🚛' },
  'americantrucksimulator.exe':     { name: 'American Truck Simulator',type: 'game', category: 'sim',  icon: '🚛' },
  'train simulator 2022.exe':        { name: 'Train Simulator 2022', type: 'game', category: 'sim',      icon: '🚂' },
  'trainsimulator2022.exe':          { name: 'Train Simulator 2022', type: 'game', category: 'sim',      icon: '🚂' },
  'train simulator.exe':             { name: 'Train Simulator',      type: 'game', category: 'sim',      icon: '🚂' },
  'trainsimulator.exe':             { name: 'Train Simulator',      type: 'game', category: 'sim',      icon: '🚂' },
  'train sim world 2.exe':          { name: 'Train Sim World 2',    type: 'game', category: 'sim',      icon: '🚂' },
  'trainsimworld2.exe':             { name: 'Train Sim World 2',    type: 'game', category: 'sim',      icon: '🚂' },
  'train sim world.exe':            { name: 'Train Sim World',      type: 'game', category: 'sim',      icon: '🚂' },
  'trainsimworld.exe':              { name: 'Train Sim World',      type: 'game', category: 'sim',      icon: '🚂' },
  'flight simulator 2020.exe':       { name: 'Microsoft Flight Simulator 2020',type: 'game', category: 'sim', icon: '✈️' },
  'flightsimulator2020.exe':         { name: 'Microsoft Flight Simulator 2020',type: 'game', category: 'sim', icon: '✈️' },
  'flight simulator x.exe':          { name: 'Flight Simulator X',   type: 'game', category: 'sim',      icon: '✈️' },
  'flightsimulatorx.exe':            { name: 'Flight Simulator X',   type: 'game', category: 'sim',      icon: '✈️' },
  'x-plane 12.exe':                 { name: 'X-Plane 12',           type: 'game', category: 'sim',      icon: '✈️' },
  'xplane12.exe':                    { name: 'X-Plane 12',           type: 'game', category: 'sim',      icon: '✈️' },
  'x-plane 11.exe':                 { name: 'X-Plane 11',           type: 'game', category: 'sim',      icon: '✈️' },
  'xplane11.exe':                    { name: 'X-Plane 11',           type: 'game', category: 'sim',      icon: '✈️' },
  'kerbal space program 2.exe':     { name: 'Kerbal Space Program 2',type: 'game', category: 'sim',      icon: '🚀' },
  'kerbalspaceprogram2.exe':        { name: 'Kerbal Space Program 2',type: 'game', category: 'sim',      icon: '🚀' },
  'kerbal space program.exe':       { name: 'Kerbal Space Program', type: 'game', category: 'sim',      icon: '🚀' },
  'kerbalspaceprogram.exe':         { name: 'Kerbal Space Program', type: 'game', category: 'sim',      icon: '🚀' },
  'simpleplanes.exe':                { name: 'SimplePlanes',         type: 'game', category: 'sim',      icon: '✈️' },
  'city car driving.exe':            { name: 'City Car Driving',     type: 'game', category: 'sim',      icon: '🚗' },
  'citycardriving.exe':             { name: 'City Car Driving',     type: 'game', category: 'sim',      icon: '🚗' },
  'beamng.drive.exe':               { name: 'BeamNG.drive',         type: 'game', category: 'sim',      icon: '🚗' },
  'beamngdrive.exe':                { name: 'BeamNG.drive',         type: 'game', category: 'sim',      icon: '🚗' },
  'assetto corsa.exe':              { name: 'Assetto Corsa',        type: 'game', category: 'sim',      icon: '🏎️' },
  'assettocorsa.exe':               { name: 'Assetto Corsa',        type: 'game', category: 'sim',      icon: '🏎️' },
  'assetto corsa competizione.exe': { name: 'Assetto Corsa Competizione',type: 'game', category: 'sim', icon: '🏎️' },
  'assettocorsacompetizione.exe':   { name: 'Assetto Corsa Competizione',type: 'game', category: 'sim', icon: '🏎️' },
  'rfactor 2.exe':                  { name: 'rFactor 2',            type: 'game', category: 'sim',      icon: '🏎️' },
  'rfactor2.exe':                   { name: 'rFactor 2',            type: 'game', category: 'sim',      icon: '🏎️' },
  'rfactor.exe':                    { name: 'rFactor',              type: 'game', category: 'sim',      icon: '🏎️' },
  'automobilista 2.exe':            { name: 'Automobilista 2',      type: 'game', category: 'sim',      icon: '🏎️' },
  'automobilista2.exe':             { name: 'Automobilista 2',      type: 'game', category: 'sim',      icon: '🏎️' },
  'automobilista.exe':              { name: 'Automobilista',        type: 'game', category: 'sim',      icon: '🏎️' },
  'project cars 2.exe':             { name: 'Project CARS 2',      type: 'game', category: 'sim',      icon: '🏎️' },
  'projectcars2.exe':               { name: 'Project CARS 2',      type: 'game', category: 'sim',      icon: '🏎️' },
  'project cars.exe':               { name: 'Project CARS',        type: 'game', category: 'sim',      icon: '🏎️' },
  'projectcars.exe':                { name: 'Project CARS',        type: 'game', category: 'sim',      icon: '🏎️' },
  'dirt rally 2.0.exe':             { name: 'DiRT Rally 2.0',      type: 'game', category: 'sim',      icon: '🚗' },
  'dirtrally2.exe':                 { name: 'DiRT Rally 2.0',      type: 'game', category: 'sim',      icon: '🚗' },
  'dirt rally.exe':                { name: 'DiRT Rally',          type: 'game', category: 'sim',      icon: '🚗' },
  'dirtrally.exe':                  { name: 'DiRT Rally',          type: 'game', category: 'sim',      icon: '🚗' },
  'f1 2023.exe':                    { name: 'F1 2023',             type: 'game', category: 'sim',      icon: '🏎️' },
  'f12023.exe':                     { name: 'F1 2023',             type: 'game', category: 'sim',      icon: '🏎️' },
  'f1 2024.exe':                    { name: 'F1 2024',             type: 'game', category: 'sim',      icon: '🏎️' },
  'f12024.exe':                     { name: 'F1 2024',             type: 'game', category: 'sim',      icon: '🏎️' },
  'bus simulator 21.exe':           { name: 'Bus Simulator 21',     type: 'game', category: 'sim',      icon: '🚌' },
  'bussimulator21.exe':             { name: 'Bus Simulator 21',     type: 'game', category: 'sim',      icon: '🚌' },
  'bus simulator 18.exe':           { name: 'Bus Simulator 18',     type: 'game', category: 'sim',      icon: '🚌' },
  'bussimulator18.exe':             { name: 'Bus Simulator 18',     type: 'game', category: 'sim',      icon: '🚌' },
  'car mechanic simulator 2021.exe': { name: 'Car Mechanic Simulator 2021',type: 'game', category: 'sim', icon: '🔧' },
  'carmechanicsimulator2021.exe':   { name: 'Car Mechanic Simulator 2021',type: 'game', category: 'sim', icon: '🔧' },
  'car mechanic simulator 2018.exe': { name: 'Car Mechanic Simulator 2018',type: 'game', category: 'sim', icon: '🔧' },
  'carmechanicsimulator2018.exe':   { name: 'Car Mechanic Simulator 2018',type: 'game', category: 'sim', icon: '🔧' },
  'construction simulator.exe':     { name: 'Construction Simulator',type: 'game', category: 'sim',      icon: '🏗️' },
  'constructionsimulator.exe':      { name: 'Construction Simulator',type: 'game', category: 'sim',      icon: '🏗️' },
  'fishing simulator.exe':          { name: 'Fishing Simulator',    type: 'game', category: 'sim',      icon: '🎣' },
  'fishingsimulator.exe':           { name: 'Fishing Simulator',    type: 'game', category: 'sim',      icon: '🎣' },
  'the hunter call of the wild.exe': { name: 'theHunter: Call of the Wild',type: 'game', category: 'sim', icon: '🦌' },
  'thehuntercallofthewild.exe':     { name: 'theHunter: Call of the Wild',type: 'game', category: 'sim', icon: '🦌' },
  'planet zoo.exe':                 { name: 'Planet Zoo',           type: 'game', category: 'sim',      icon: '🦁' },
  'planetzoo.exe':                  { name: 'Planet Zoo',           type: 'game', category: 'sim',      icon: '🦁' },
  'planet coaster.exe':             { name: 'Planet Coaster',       type: 'game', category: 'sim',      icon: '🎢' },
  'planetcoaster.exe':              { name: 'Planet Coaster',       type: 'game', category: 'sim',      icon: '🎢' },
  'jurassic world evolution 2.exe': { name: 'Jurassic World Evolution 2',type: 'game', category: 'sim', icon: '🦖' },
  'jurassicworldevolution2.exe':   { name: 'Jurassic World Evolution 2',type: 'game', category: 'sim', icon: '🦖' },
  'jurassic world evolution.exe':   { name: 'Jurassic World Evolution',type: 'game', category: 'sim', icon: '🦖' },
  'jurassicworldevolution.exe':    { name: 'Jurassic World Evolution',type: 'game', category: 'sim', icon: '🦖' },
  'parkitect.exe':                  { name: 'Parkitect',            type: 'game', category: 'sim',      icon: '🎢' },
  'rollercoaster tycoon 3.exe':     { name: 'RollerCoaster Tycoon 3',type: 'game', category: 'sim',      icon: '🎢' },
  'rollercoastertycoon3.exe':       { name: 'RollerCoaster Tycoon 3',type: 'game', category: 'sim',      icon: '🎢' },
  'rollercoaster tycoon 2.exe':     { name: 'RollerCoaster Tycoon 2',type: 'game', category: 'sim',      icon: '🎢' },
  'rollercoastertycoon2.exe':       { name: 'RollerCoaster Tycoon 2',type: 'game', category: 'sim',      icon: '🎢' },
  'rollercoaster tycoon.exe':       { name: 'RollerCoaster Tycoon',  type: 'game', category: 'sim',      icon: '🎢' },
  'rollercoastertycoon.exe':        { name: 'RollerCoaster Tycoon',  type: 'game', category: 'sim',      icon: '🎢' },
  'two point hospital.exe':         { name: 'Two Point Hospital',   type: 'game', category: 'sim',      icon: '🏥' },
  'twopointhospital.exe':           { name: 'Two Point Hospital',   type: 'game', category: 'sim',      icon: '🏥' },
  'two point campus.exe':           { name: 'Two Point Campus',     type: 'game', category: 'sim',      icon: '🎓' },
  'twopointcampus.exe':             { name: 'Two Point Campus',     type: 'game', category: 'sim',      icon: '🎓' },
  'theme hospital.exe':            { name: 'Theme Hospital',       type: 'game', category: 'sim',      icon: '🏥' },
  'themehospital.exe':              { name: 'Theme Hospital',       type: 'game', category: 'sim',      icon: '🏥' },
  'prison architect.exe':           { name: 'Prison Architect',     type: 'game', category: 'sim',      icon: '🏢' },
  'prisonarchitect.exe':            { name: 'Prison Architect',     type: 'game', category: 'sim',      icon: '🏢' },
  'rimworld.exe':                   { name: 'RimWorld',            type: 'game', category: 'sim',      icon: '🌍' },
  'dwarf fortress.exe':            { name: 'Dwarf Fortress',      type: 'game', category: 'sim',      icon: '⛏️' },
  'dwarffortress.exe':             { name: 'Dwarf Fortress',      type: 'game', category: 'sim',      icon: '⛏️' },
  'factorio.exe':                   { name: 'Factorio',             type: 'game', category: 'sim',      icon: '⚙️' },
  'satisfactory.exe':              { name: 'Satisfactory',         type: 'game', category: 'sim',      icon: '🏭' },
  'dyson sphere program.exe':      { name: 'Dyson Sphere Program', type: 'game', category: 'sim',      icon: '🌐' },
  'dysonsphereprogram.exe':         { name: 'Dyson Sphere Program', type: 'game', category: 'sim',      icon: '🌐' },
  'mindustry.exe':                 { name: 'Mindustry',            type: 'game', category: 'sim',      icon: '⚙️' },
  'zachtronics games.exe':         { name: 'Zachtronics Games',    type: 'game', category: 'sim',      icon: '💻' },
  'openttd.exe':                    { name: 'OpenTTD',              type: 'game', category: 'sim',      icon: '🚂' },
  'simutrans.exe':                 { name: 'Simutrans',            type: 'game', category: 'sim',      icon: '🚂' },
  'transport fever 2.exe':         { name: 'Transport Fever 2',    type: 'game', category: 'sim',      icon: '🚂' },
  'transportfever2.exe':           { name: 'Transport Fever 2',    type: 'game', category: 'sim',      icon: '🚂' },
  'transport fever.exe':           { name: 'Transport Fever',      type: 'game', category: 'sim',      icon: '🚂' },
  'transportfever.exe':             { name: 'Transport Fever',      type: 'game', category: 'sim',      icon: '🚂' },
  'cities in motion 2.exe':        { name: 'Cities in Motion 2',   type: 'game', category: 'sim',      icon: '🚌' },
  'citiesinmotion2.exe':           { name: 'Cities in Motion 2',   type: 'game', category: 'sim',      icon: '🚌' },
  'cities in motion.exe':          { name: 'Cities in Motion',      type: 'game', category: 'sim',      icon: '🚌' },
  'citiesinmotion.exe':            { name: 'Cities in Motion',      type: 'game', category: 'sim',      icon: '🚌' },
  'surgeon simulator.exe':         { name: 'Surgeon Simulator',    type: 'game', category: 'sim',      icon: '🏥' },
  'surgeonsimulator.exe':          { name: 'Surgeon Simulator',    type: 'game', category: 'sim',      icon: '🏥' },
  'surgeon simulator 2.exe':       { name: 'Surgeon Simulator 2',  type: 'game', category: 'sim',      icon: '🏥' },
  'surgeonsimulator2.exe':         { name: 'Surgeon Simulator 2',  type: 'game', category: 'sim',      icon: '🏥' },
  'goat simulator.exe':            { name: 'Goat Simulator',       type: 'game', category: 'sim',      icon: '🐐' },
  'goatsimulator.exe':             { name: 'Goat Simulator',       type: 'game', category: 'sim',      icon: '🐐' },
  'i am bread.exe':               { name: 'I Am Bread',           type: 'game', category: 'sim',      icon: '🍞' },
  'iambread.exe':                  { name: 'I Am Bread',           type: 'game', category: 'sim',      icon: '🍞' },
  'rock simulator.exe':           { name: 'Rock Simulator',       type: 'game', category: 'sim',      icon: '🪨' },
  'rocksimulator.exe':             { name: 'Rock Simulator',       type: 'game', category: 'sim',      icon: '🪨' },
  'grass simulator.exe':          { name: 'Grass Simulator',      type: 'game', category: 'sim',      icon: '🌿' },
  'grasssimulator.exe':            { name: 'Grass Simulator',      type: 'game', category: 'sim',      icon: '🌿' },
  'powerwash simulator.exe':      { name: 'PowerWash Simulator',  type: 'game', category: 'sim',      icon: '💦' },
  'powerwashsimulator.exe':        { name: 'PowerWash Simulator',  type: 'game', category: 'sim',      icon: '💦' },
  'house flipper.exe':            { name: 'House Flipper',        type: 'game', category: 'sim',      icon: '🏠' },
  'houseflipper.exe':              { name: 'House Flipper',        type: 'game', category: 'sim',      icon: '🏠' },
  'garden paws.exe':              { name: 'Garden Paws',          type: 'game', category: 'sim',      icon: '🐾' },
  'gardenpaws.exe':                { name: 'Garden Paws',          type: 'game', category: 'sim',      icon: '🐾' },
  'stardew valley.exe':           { name: 'Stardew Valley',       type: 'game', category: 'sim',      icon: '🌾' },
  'stardewvalley.exe':             { name: 'Stardew Valley',       type: 'game', category: 'sim',      icon: '🌾' },
  'graveyard keeper.exe':         { name: 'Graveyard Keeper',     type: 'game', category: 'sim',      icon: '⚰️' },
  'graveyardkeeper.exe':           { name: 'Graveyard Keeper',     type: 'game', category: 'sim',      icon: '⚰️' },
  'spiritfarer.exe':              { name: 'Spiritfarer',          type: 'game', category: 'sim',      icon: '⛵' },
  'cozy grove.exe':               { name: 'Cozy Grove',           type: 'game', category: 'sim',      icon: '🌲' },
  'cozygrove.exe':                 { name: 'Cozy Grove',           type: 'game', category: 'sim',      icon: '🌲' },
  'animal crossing new horizons.exe': { name: 'Animal Crossing: New Horizons',type: 'game', category: 'sim', icon: '🏝️' },
  'animalcrossingnewhorizons.exe': { name: 'Animal Crossing: New Horizons',type: 'game', category: 'sim', icon: '🏝️' },
  'animal crossing.exe':          { name: 'Animal Crossing',      type: 'game', category: 'sim',      icon: '🏝️' },
  'animalcrossing.exe':            { name: 'Animal Crossing',      type: 'game', category: 'sim',      icon: '🏝️' },
  'harvest moon.exe':             { name: 'Harvest Moon',          type: 'game', category: 'sim',      icon: '🌾' },
  'harvestmoon.exe':               { name: 'Harvest Moon',          type: 'game', category: 'sim',      icon: '🌾' },
  'story of seasons.exe':         { name: 'Story of Seasons',      type: 'game', category: 'sim',      icon: '🌾' },
  'storyofseasons.exe':            { name: 'Story of Seasons',      type: 'game', category: 'sim',      icon: '🌾' },
  'yonder the cloud catcher.exe': { name: 'Yonder: The Cloud Catcher',type: 'game', category: 'sim', icon: '☁️' },
  'yonderthecloudcatcher.exe':    { name: 'Yonder: The Cloud Catcher',type: 'game', category: 'sim', icon: '☁️' },
  'a short hike.exe':             { name: 'A Short Hike',         type: 'game', category: 'sim',      icon: '🦅' },
  'ashorthike.exe':                { name: 'A Short Hike',         type: 'game', category: 'sim',      icon: '🦅' },
  'venba.exe':                     { name: 'Venba',               type: 'game', category: 'sim',      icon: '🍛' },
  'calico.exe':                    { name: 'Calico',              type: 'game', category: 'sim',      icon: '🐱' },
  'pupperazzi.exe':               { name: 'Pupperazzi',           type: 'game', category: 'sim',      icon: '🐕' },
  'nintendogs.exe':               { name: 'Nintendogs',           type: 'game', category: 'sim',      icon: '🐕' },
  'nintendogs cats.exe':          { name: 'Nintendogs + Cats',    type: 'game', category: 'sim',      icon: '🐱' },
  'nintendogscats.exe':           { name: 'Nintendogs + Cats',    type: 'game', category: 'sim',      icon: '🐱' },
  'tamagotchi.exe':               { name: 'Tamagotchi',           type: 'game', category: 'sim',      icon: '🥚' },
  'little friends.exe':          { name: 'Little Friends',       type: 'game', category: 'sim',      icon: '🐕' },
  'littlefriends.exe':            { name: 'Little Friends',       type: 'game', category: 'sim',      icon: '🐕' },
  'the sims 4.exe':              { name: 'The Sims 4',           type: 'game', category: 'sim',      icon: '🏠' },
  'thesims4.exe':                 { name: 'The Sims 4',           type: 'game', category: 'sim',      icon: '🏠' },
  'the sims 3.exe':              { name: 'The Sims 3',           type: 'game', category: 'sim',      icon: '🏠' },
  'thesims3.exe':                 { name: 'The Sims 3',           type: 'game', category: 'sim',      icon: '🏠' },
  'the sims 2.exe':              { name: 'The Sims 2',           type: 'game', category: 'sim',      icon: '🏠' },
  'thesims2.exe':                 { name: 'The Sims 2',           type: 'game', category: 'sim',      icon: '🏠' },
  'the sims.exe':                { name: 'The Sims',             type: 'game', category: 'sim',      icon: '🏠' },
  'thesims.exe':                  { name: 'The Sims',             type: 'game', category: 'sim',      icon: '🏠' },
  'the sims medieval.exe':       { name: 'The Sims Medieval',    type: 'game', category: 'sim',      icon: '🏰' },
  'thesimsmedieval.exe':          { name: 'The Sims Medieval',    type: 'game', category: 'sim',      icon: '🏰' },
  'the sims castaway.exe':       { name: 'The Sims Castaway',    type: 'game', category: 'sim',      icon: '🏝️' },
  'thesimscastaway.exe':         { name: 'The Sims Castaway',    type: 'game', category: 'sim',      icon: '🏝️' },
  'the sims bustin out.exe':     { name: 'The Sims Bustin\' Out',type: 'game', category: 'sim',      icon: '🏠' },
  'thesimsbustinout.exe':        { name: 'The Sims Bustin\' Out',type: 'game', category: 'sim',      icon: '🏠' },
  'the sims 2 pets.exe':        { name: 'The Sims 2: Pets',     type: 'game', category: 'sim',      icon: '🐕' },
  'thesims2pets.exe':           { name: 'The Sims 2: Pets',     type: 'game', category: 'sim',      icon: '🐕' },
  'the sims 2 seasons.exe':     { name: 'The Sims 2: Seasons',  type: 'game', category: 'sim',      icon: '🍂' },
  'thesims2seasons.exe':        { name: 'The Sims 2: Seasons',  type: 'game', category: 'sim',      icon: '🍂' },
  'the sims 2 nightlife.exe':   { name: 'The Sims 2: Nightlife',type: 'game', category: 'sim',      icon: '🌃' },
  'thesims2nightlife.exe':      { name: 'The Sims 2: Nightlife',type: 'game', category: 'sim',      icon: '🌃' },
  'the sims 2 university.exe': { name: 'The Sims 2: University',type: 'game', category: 'sim',      icon: '🎓' },
  'thesims2university.exe':    { name: 'The Sims 2: University',type: 'game', category: 'sim',      icon: '🎓' },
  'the sims 2 open for business.exe': { name: 'The Sims 2: Open for Business',type: 'game', category: 'sim', icon: '💼' },
  'thesims2openforbusiness.exe': { name: 'The Sims 2: Open for Business',type: 'game', category: 'sim', icon: '💼' },
  'the sims 2 bon voyage.exe': { name: 'The Sims 2: Bon Voyage',type: 'game', category: 'sim',      icon: '✈️' },
  'thesims2bonvoyage.exe':    { name: 'The Sims 2: Bon Voyage',type: 'game', category: 'sim',      icon: '✈️' },
  'the sims 2 free time.exe': { name: 'The Sims 2: Free Time',type: 'game', category: 'sim',      icon: '⏰' },
  'thesims2freetime.exe':    { name: 'The Sims 2: Free Time',type: 'game', category: 'sim',      icon: '⏰' },
  'the sims 2 apartment life.exe': { name: 'The Sims 2: Apartment Life',type: 'game', category: 'sim', icon: '🏢' },
  'thesims2apartmentlife.exe': { name: 'The Sims 2: Apartment Life',type: 'game', category: 'sim', icon: '🏢' },
  'the sims 3 ambitions.exe': { name: 'The Sims 3: Ambitions',type: 'game', category: 'sim',      icon: '💼' },
  'thesims3ambitions.exe':    { name: 'The Sims 3: Ambitions',type: 'game', category: 'sim',      icon: '💼' },
  'the sims 3 late night.exe': { name: 'The Sims 3: Late Night',type: 'game', category: 'sim',      icon: '🌃' },
  'thesims3latenight.exe':    { name: 'The Sims 3: Late Night',type: 'game', category: 'sim',      icon: '🌃' },
  'the sims 3 generations.exe': { name: 'The Sims 3: Generations',type: 'game', category: 'sim', icon: '👨‍👩‍👧' },
  'thesims3generations.exe': { name: 'The Sims 3: Generations',type: 'game', category: 'sim', icon: '👨‍👩‍👧' },
  'the sims 3 pets.exe':      { name: 'The Sims 3: Pets',     type: 'game', category: 'sim',      icon: '🐕' },
  'thesims3pets.exe':         { name: 'The Sims 3: Pets',     type: 'game', category: 'sim',      icon: '🐕' },
  'the sims 3 showtime.exe': { name: 'The Sims 3: Showtime', type: 'game', category: 'sim',      icon: '🎭' },
  'thesims3showtime.exe':    { name: 'The Sims 3: Showtime', type: 'game', category: 'sim',      icon: '🎭' },
  'the sims 3 supernatural.exe': { name: 'The Sims 3: Supernatural',type: 'game', category: 'sim', icon: '🧛' },
  'thesims3supernatural.exe': { name: 'The Sims 3: Supernatural',type: 'game', category: 'sim', icon: '🧛' },
  'the sims 3 seasons.exe': { name: 'The Sims 3: Seasons', type: 'game', category: 'sim',      icon: '🍂' },
  'thesims3seasons.exe':    { name: 'The Sims 3: Seasons', type: 'game', category: 'sim',      icon: '🍂' },
  'the sims 3 university life.exe': { name: 'The Sims 3: University Life',type: 'game', category: 'sim', icon: '🎓' },
  'thesims3universitylife.exe': { name: 'The Sims 3: University Life',type: 'game', category: 'sim', icon: '🎓' },
};
