/**
 * Descall Process Detection Database
 * 900+ curated entries — add new entries without touching detection logic.
 *
 * Schema per entry:
 *   key  : exact .exe filename, lowercase
 *   value: { name, type, category, icon }
 *
 * type     : 'game' | 'music' | 'dev' | 'browser' | 'productivity' |
 *            'communication' | 'media' | 'launcher' | 'creative' | 'app'
 * category : human-readable sub-category for grouping
 * icon     : emoji fallback (used when no custom icon is available)
 */

export const PROCESS_DB = {
  // ─── FPS / TACTICAL SHOOTERS ────────────────────────────────────────────────
  'valorant-win64-shipping.exe':       { name: 'Valorant',            type: 'game', category: 'fps',      icon: '🎮' },
  'csgo.exe':                          { name: 'CS:GO',               type: 'game', category: 'fps',      icon: '🎮' },
  'cs2.exe':                           { name: 'Counter-Strike 2',    type: 'game', category: 'fps',      icon: '🎮' },
  'r5apex.exe':                        { name: 'Apex Legends',        type: 'game', category: 'fps',      icon: '🎮' },
  'overwatch.exe':                     { name: 'Overwatch 2',         type: 'game', category: 'fps',      icon: '🎮' },
  'overwatch2.exe':                    { name: 'Overwatch 2',         type: 'game', category: 'fps',      icon: '🎮' },
  'cod.exe':                           { name: 'Call of Duty',        type: 'game', category: 'fps',      icon: '🎮' },
  'modernwarfare.exe':                 { name: 'Modern Warfare',      type: 'game', category: 'fps',      icon: '🎮' },
  'warzone.exe':                       { name: 'Warzone',             type: 'game', category: 'fps',      icon: '🎮' },
  'cod_hq.exe':                        { name: 'Call of Duty HQ',     type: 'game', category: 'fps',      icon: '🎮' },
  'mw2.exe':                           { name: 'MW2',                 type: 'game', category: 'fps',      icon: '🎮' },
  'mw3.exe':                           { name: 'MW3',                 type: 'game', category: 'fps',      icon: '🎮' },
  'bo6.exe':                           { name: 'Black Ops 6',         type: 'game', category: 'fps',      icon: '🎮' },
  'rainbow6.exe':                      { name: 'Rainbow Six Siege',   type: 'game', category: 'fps',      icon: '🎮' },
  'rainbowsix.exe':                    { name: 'Rainbow Six Siege',   type: 'game', category: 'fps',      icon: '🎮' },
  'bf1.exe':                           { name: 'Battlefield 1',       type: 'game', category: 'fps',      icon: '🎮' },
  'bf2042.exe':                        { name: 'Battlefield 2042',    type: 'game', category: 'fps',      icon: '🎮' },
  'bf4.exe':                           { name: 'Battlefield 4',       type: 'game', category: 'fps',      icon: '🎮' },
  'bfv.exe':                           { name: 'Battlefield V',       type: 'game', category: 'fps',      icon: '🎮' },
  'halo.exe':                          { name: 'Halo Infinite',       type: 'game', category: 'fps',      icon: '🎮' },
  'haloinfinite.exe':                  { name: 'Halo Infinite',       type: 'game', category: 'fps',      icon: '🎮' },
  'splitgate.exe':                     { name: 'Splitgate',           type: 'game', category: 'fps',      icon: '🎮' },
  'insurgency.exe':                    { name: 'Insurgency',          type: 'game', category: 'fps',      icon: '🎮' },
  'sandstorm.exe':                     { name: 'Insurgency Sandstorm',type: 'game', category: 'fps',      icon: '🎮' },
  'xdefiant.exe':                      { name: 'XDefiant',            type: 'game', category: 'fps',      icon: '🎮' },
  'hunt.exe':                          { name: 'Hunt: Showdown',      type: 'game', category: 'fps',      icon: '🎮' },
  'tarkov.exe':                        { name: 'Escape from Tarkov',  type: 'game', category: 'fps',      icon: '🎮' },
  'escapefromtarkov.exe':              { name: 'Escape from Tarkov',  type: 'game', category: 'fps',      icon: '🎮' },
  'deeprock.exe':                      { name: 'Deep Rock Galactic',  type: 'game', category: 'fps',      icon: '🎮' },
  'farcry6.exe':                       { name: 'Far Cry 6',           type: 'game', category: 'fps',      icon: '🎮' },
  'paladins.exe':                      { name: 'Paladins',            type: 'game', category: 'fps',      icon: '🎮' },
  'quake.exe':                         { name: 'Quake Champions',     type: 'game', category: 'fps',      icon: '🎮' },
  'hyperscape.exe':                    { name: 'Hyper Scape',         type: 'game', category: 'fps',      icon: '🎮' },
  'readyornot.exe':                    { name: 'Ready or Not',        type: 'game', category: 'fps',      icon: '🎮' },
  'ground branch.exe':                 { name: 'Ground Branch',       type: 'game', category: 'fps',      icon: '🎮' },
  'contractorsvr.exe':                 { name: 'Contractors VR',      type: 'game', category: 'fps',      icon: '🎮' },

  // ─── BATTLE ROYALE ──────────────────────────────────────────────────────────
  'fortniteclient-win64-shipping.exe': { name: 'Fortnite',            type: 'game', category: 'battle-royale', icon: '🎮' },
  'pubg.exe':                          { name: 'PUBG',                type: 'game', category: 'battle-royale', icon: '🎮' },
  'tslgame.exe':                       { name: 'PUBG',                type: 'game', category: 'battle-royale', icon: '🎮' },
  'freefire.exe':                      { name: 'Free Fire',           type: 'game', category: 'battle-royale', icon: '🎮' },
  'fallguys.exe':                      { name: 'Fall Guys',           type: 'game', category: 'battle-royale', icon: '🎮' },
  'naraka.exe':                        { name: 'Naraka: Bladepoint',  type: 'game', category: 'battle-royale', icon: '🎮' },
  'narakabladepoint.exe':              { name: 'Naraka: Bladepoint',  type: 'game', category: 'battle-royale', icon: '🎮' },
  'bloodhunt.exe':                     { name: 'Bloodhunt',           type: 'game', category: 'battle-royale', icon: '🎮' },
  'darwin.exe':                        { name: 'Darwin Project',      type: 'game', category: 'battle-royale', icon: '🎮' },

  // ─── MOBA ───────────────────────────────────────────────────────────────────
  'dota2.exe':                         { name: 'Dota 2',              type: 'game', category: 'moba',     icon: '🎮' },
  'league of legends.exe':             { name: 'League of Legends',   type: 'game', category: 'moba',     icon: '🎮' },
  'leagueoflegends.exe':               { name: 'League of Legends',   type: 'game', category: 'moba',     icon: '🎮' },
  'wildrift.exe':                      { name: 'Wild Rift',           type: 'game', category: 'moba',     icon: '🎮' },
  'smite.exe':                         { name: 'SMITE',               type: 'game', category: 'moba',     icon: '🎮' },
  'heroesofthestorm.exe':              { name: 'Heroes of the Storm', type: 'game', category: 'moba',     icon: '🎮' },
  'deadlock.exe':                      { name: 'Deadlock',            type: 'game', category: 'moba',     icon: '🎮' },
  'predecessor.exe':                   { name: 'Predecessor',         type: 'game', category: 'moba',     icon: '🎮' },

  // ─── SANDBOX / OPEN WORLD ───────────────────────────────────────────────────
  'gta5.exe':                          { name: 'GTA V',               type: 'game', category: 'sandbox',  icon: '🎮' },
  'gta_sa.exe':                        { name: 'GTA San Andreas',     type: 'game', category: 'sandbox',  icon: '🎮' },
  'javaw.exe':                         { name: 'Minecraft',           type: 'game', category: 'sandbox',  icon: '⛏️' },
  'minecraftlauncher.exe':             { name: 'Minecraft Launcher',  type: 'game', category: 'sandbox',  icon: '⛏️' },
  'robloxplayerbeta.exe':              { name: 'Roblox',              type: 'game', category: 'sandbox',  icon: '🎮' },
  'robloxstudiobeta.exe':              { name: 'Roblox Studio',       type: 'game', category: 'sandbox',  icon: '🎮' },
  'fivem.exe':                         { name: 'FiveM',               type: 'game', category: 'sandbox',  icon: '🎮' },
  'fivemapplication.exe':              { name: 'FiveM',               type: 'game', category: 'sandbox',  icon: '🎮' },
  'arma3.exe':                         { name: 'Arma 3',              type: 'game', category: 'sandbox',  icon: '🎮' },
  'arma3launcher.exe':                 { name: 'Arma 3',              type: 'game', category: 'sandbox',  icon: '🎮' },
  'dayz.exe':                          { name: 'DayZ',                type: 'game', category: 'sandbox',  icon: '🎮' },
  'rust.exe':                          { name: 'Rust',                type: 'game', category: 'sandbox',  icon: '🎮' },
  'empyrion.exe':                      { name: 'Empyrion',            type: 'game', category: 'sandbox',  icon: '🎮' },
  'terasology.exe':                    { name: 'Terasology',          type: 'game', category: 'sandbox',  icon: '🎮' },
  'factorio.exe':                      { name: 'Factorio',            type: 'game', category: 'sandbox',  icon: '🎮' },
  'satisfactory.exe':                  { name: 'Satisfactory',        type: 'game', category: 'sandbox',  icon: '🎮' },
  'terraria.exe':                      { name: 'Terraria',            type: 'game', category: 'sandbox',  icon: '🎮' },
  'starbound.exe':                     { name: 'Starbound',           type: 'game', category: 'sandbox',  icon: '🎮' },
  'stardewvalley.exe':                 { name: 'Stardew Valley',      type: 'game', category: 'sandbox',  icon: '🌾' },
  'subnautica.exe':                    { name: 'Subnautica',          type: 'game', category: 'sandbox',  icon: '🎮' },
  'nomansskygame.exe':                 { name: "No Man's Sky",        type: 'game', category: 'sandbox',  icon: '🎮' },
  'astroneer.exe':                     { name: 'Astroneer',           type: 'game', category: 'sandbox',  icon: '🎮' },
  'theforest.exe':                     { name: 'The Forest',          type: 'game', category: 'sandbox',  icon: '🎮' },
  'sonsoftheforest.exe':               { name: 'Sons of the Forest',  type: 'game', category: 'sandbox',  icon: '🎮' },
  'valheim.exe':                       { name: 'Valheim',             type: 'game', category: 'sandbox',  icon: '🎮' },
  'conanexiles.exe':                   { name: 'Conan Exiles',        type: 'game', category: 'sandbox',  icon: '🎮' },
  'scum.exe':                          { name: 'SCUM',                type: 'game', category: 'sandbox',  icon: '🎮' },
  'theislebeta-win64-shipping.exe':    { name: 'The Isle',            type: 'game', category: 'sandbox',  icon: '🎮' },
  'raft.exe':                          { name: 'Raft',                type: 'game', category: 'sandbox',  icon: '🎮' },
  'grounded.exe':                      { name: 'Grounded',            type: 'game', category: 'sandbox',  icon: '🎮' },
  'stranded deep.exe':                 { name: 'Stranded Deep',       type: 'game', category: 'sandbox',  icon: '🎮' },
  'icarus.exe':                        { name: 'Icarus',              type: 'game', category: 'sandbox',  icon: '🎮' },

  // ─── RPG / MMO ──────────────────────────────────────────────────────────────
  'witcher3.exe':                      { name: 'The Witcher 3',       type: 'game', category: 'rpg',      icon: '⚔️' },
  'cyberpunk2077.exe':                 { name: 'Cyberpunk 2077',      type: 'game', category: 'rpg',      icon: '⚔️' },
  'eldenring.exe':                     { name: 'Elden Ring',          type: 'game', category: 'rpg',      icon: '⚔️' },
  'darksouls3.exe':                    { name: 'Dark Souls 3',        type: 'game', category: 'rpg',      icon: '⚔️' },
  'darksoulsiii.exe':                  { name: 'Dark Souls III',      type: 'game', category: 'rpg',      icon: '⚔️' },
  'sekiro.exe':                        { name: 'Sekiro',              type: 'game', category: 'rpg',      icon: '⚔️' },
  'baldursgate3.exe':                  { name: "Baldur's Gate 3",     type: 'game', category: 'rpg',      icon: '⚔️' },
  'bg3.exe':                           { name: "Baldur's Gate 3",     type: 'game', category: 'rpg',      icon: '⚔️' },
  'pathofexile.exe':                   { name: 'Path of Exile',       type: 'game', category: 'rpg',      icon: '⚔️' },
  'pathofexile2.exe':                  { name: 'Path of Exile 2',     type: 'game', category: 'rpg',      icon: '⚔️' },
  'diablo4.exe':                       { name: 'Diablo IV',           type: 'game', category: 'rpg',      icon: '⚔️' },
  'diablo3.exe':                       { name: 'Diablo III',          type: 'game', category: 'rpg',      icon: '⚔️' },
  'wowclassic.exe':                    { name: 'WoW Classic',         type: 'game', category: 'mmo',      icon: '⚔️' },
  'wow.exe':                           { name: 'World of Warcraft',   type: 'game', category: 'mmo',      icon: '⚔️' },
  'ffxiv.exe':                         { name: 'Final Fantasy XIV',   type: 'game', category: 'mmo',      icon: '⚔️' },
  'ffxivlauncher.exe':                 { name: 'Final Fantasy XIV',   type: 'game', category: 'mmo',      icon: '⚔️' },
  'gw2-64.exe':                        { name: 'Guild Wars 2',        type: 'game', category: 'mmo',      icon: '⚔️' },
  'eso.exe':                           { name: 'Elder Scrolls Online',type: 'game', category: 'mmo',      icon: '⚔️' },
  'newworld.exe':                      { name: 'New World',           type: 'game', category: 'mmo',      icon: '⚔️' },
  'lostark.exe':                       { name: 'Lost Ark',            type: 'game', category: 'mmo',      icon: '⚔️' },
  'mapleroyals.exe':                   { name: 'MapleStory',          type: 'game', category: 'mmo',      icon: '⚔️' },
  'runescape.exe':                     { name: 'RuneScape',           type: 'game', category: 'mmo',      icon: '⚔️' },
  'oldschoolrunescape.exe':            { name: 'OSRS',                type: 'game', category: 'mmo',      icon: '⚔️' },
  'black desert launcher.exe':         { name: 'Black Desert Online', type: 'game', category: 'mmo',      icon: '⚔️' },
  'albion online launcher.exe':        { name: 'Albion Online',       type: 'game', category: 'mmo',      icon: '⚔️' },
  'aion.exe':                          { name: 'Aion',                type: 'game', category: 'mmo',      icon: '⚔️' },
  'tera.exe':                          { name: 'TERA',                type: 'game', category: 'mmo',      icon: '⚔️' },
  'skyrim.exe':                        { name: 'Skyrim',              type: 'game', category: 'rpg',      icon: '⚔️' },
  'skyrimse.exe':                      { name: 'Skyrim SE',           type: 'game', category: 'rpg',      icon: '⚔️' },
  'fallout4.exe':                      { name: 'Fallout 4',           type: 'game', category: 'rpg',      icon: '⚔️' },
  'starfield.exe':                     { name: 'Starfield',           type: 'game', category: 'rpg',      icon: '⚔️' },
  'masseffectle.exe':                  { name: 'Mass Effect LE',      type: 'game', category: 'rpg',      icon: '⚔️' },
  'dragonage.exe':                     { name: 'Dragon Age',          type: 'game', category: 'rpg',      icon: '⚔️' },
  'kingdomsofamalur.exe':              { name: 'Kingdoms of Amalur',  type: 'game', category: 'rpg',      icon: '⚔️' },
  'monsterhunerworld.exe':             { name: 'Monster Hunter World',type: 'game', category: 'rpg',      icon: '⚔️' },
  'mhrise.exe':                        { name: 'Monster Hunter Rise', type: 'game', category: 'rpg',      icon: '⚔️' },
  'hogwartslegacy.exe':                { name: 'Hogwarts Legacy',     type: 'game', category: 'rpg',      icon: '⚔️' },

  // ─── STRATEGY / RTS / 4X ────────────────────────────────────────────────────
  'starcraft2.exe':                    { name: 'StarCraft II',        type: 'game', category: 'strategy', icon: '🎮' },
  'sc2.exe':                           { name: 'StarCraft II',        type: 'game', category: 'strategy', icon: '🎮' },
  'age3.exe':                          { name: 'Age of Empires III',  type: 'game', category: 'strategy', icon: '🎮' },
  'age3de.exe':                        { name: 'Age of Empires III DE',type: 'game',category: 'strategy', icon: '🎮' },
  'aoe4.exe':                          { name: 'Age of Empires IV',   type: 'game', category: 'strategy', icon: '🎮' },
  'aoe2de.exe':                        { name: 'Age of Empires II DE',type: 'game', category: 'strategy', icon: '🎮' },
  'civ6.exe':                          { name: 'Civilization VI',     type: 'game', category: 'strategy', icon: '🎮' },
  'civ7.exe':                          { name: 'Civilization VII',    type: 'game', category: 'strategy', icon: '🎮' },
  'totalwar.exe':                      { name: 'Total War',           type: 'game', category: 'strategy', icon: '🎮' },
  'humankind.exe':                     { name: 'Humankind',           type: 'game', category: 'strategy', icon: '🎮' },
  'xcom2.exe':                         { name: 'XCOM 2',              type: 'game', category: 'strategy', icon: '🎮' },
  'ageofwonders4.exe':                 { name: 'Age of Wonders 4',    type: 'game', category: 'strategy', icon: '🎮' },
  'crusaderkings3.exe':                { name: 'Crusader Kings III',  type: 'game', category: 'strategy', icon: '🎮' },
  'ck3.exe':                           { name: 'Crusader Kings III',  type: 'game', category: 'strategy', icon: '🎮' },
  'eu4.exe':                           { name: 'Europa Universalis IV',type: 'game',category: 'strategy', icon: '🎮' },
  'hoi4.exe':                          { name: 'Hearts of Iron IV',   type: 'game', category: 'strategy', icon: '🎮' },
  'stellaris.exe':                     { name: 'Stellaris',           type: 'game', category: 'strategy', icon: '🎮' },
  'victoria3.exe':                     { name: 'Victoria 3',          type: 'game', category: 'strategy', icon: '🎮' },
  'imperatorrome.exe':                 { name: 'Imperator: Rome',     type: 'game', category: 'strategy', icon: '🎮' },
  'rimworld.exe':                      { name: 'RimWorld',            type: 'game', category: 'strategy', icon: '🎮' },
  'dwarf fortress.exe':                { name: 'Dwarf Fortress',      type: 'game', category: 'strategy', icon: '🎮' },
  'prisonarchitect.exe':               { name: 'Prison Architect',    type: 'game', category: 'strategy', icon: '🎮' },
  'citiesxl.exe':                      { name: 'Cities XL',           type: 'game', category: 'strategy', icon: '🏙️' },
  'citiesskylines.exe':                { name: 'Cities: Skylines',    type: 'game', category: 'strategy', icon: '🏙️' },
  'citiesskylines2.exe':               { name: 'Cities: Skylines II', type: 'game', category: 'strategy', icon: '🏙️' },
  'frostpunk.exe':                     { name: 'Frostpunk',           type: 'game', category: 'strategy', icon: '🎮' },
  'frostpunk2.exe':                    { name: 'Frostpunk 2',         type: 'game', category: 'strategy', icon: '🎮' },

  // ─── CARD / AUTO-BATTLER ────────────────────────────────────────────────────
  'hearthstone.exe':                   { name: 'Hearthstone',         type: 'game', category: 'card',     icon: '🃏' },
  'gwent.exe':                         { name: 'Gwent',               type: 'game', category: 'card',     icon: '🃏' },
  'legends of runeterra.exe':          { name: 'Legends of Runeterra',type: 'game', category: 'card',     icon: '🃏' },
  'teambattle.exe':                    { name: 'Teamfight Tactics',   type: 'game', category: 'card',     icon: '🃏' },
  'teamfighttactics.exe':              { name: 'Teamfight Tactics',   type: 'game', category: 'card',     icon: '🃏' },
  'magicarena.exe':                    { name: 'Magic: The Gathering Arena', type: 'game', category: 'card', icon: '🃏' },
  'slay the spire.exe':                { name: 'Slay the Spire',      type: 'game', category: 'card',     icon: '🃏' },
  'inscryption.exe':                   { name: 'Inscryption',         type: 'game', category: 'card',     icon: '🃏' },

  // ─── SPORTS / RACING ────────────────────────────────────────────────────────
  'fifa24.exe':                        { name: 'FC 24',               type: 'game', category: 'sports',   icon: '⚽' },
  'eafc24.exe':                        { name: 'EA FC 24',            type: 'game', category: 'sports',   icon: '⚽' },
  'eafc25.exe':                        { name: 'EA FC 25',            type: 'game', category: 'sports',   icon: '⚽' },
  'nba2k24.exe':                       { name: 'NBA 2K24',            type: 'game', category: 'sports',   icon: '🏀' },
  'nba2k25.exe':                       { name: 'NBA 2K25',            type: 'game', category: 'sports',   icon: '🏀' },
  'forza_horizon5.exe':                { name: 'Forza Horizon 5',     type: 'game', category: 'racing',   icon: '🏎️' },
  'forza_motorsport.exe':              { name: 'Forza Motorsport',    type: 'game', category: 'racing',   icon: '🏎️' },
  'f12023.exe':                        { name: 'F1 2023',             type: 'game', category: 'racing',   icon: '🏎️' },
  'f12024.exe':                        { name: 'F1 24',               type: 'game', category: 'racing',   icon: '🏎️' },
  'assettocorsa.exe':                  { name: 'Assetto Corsa',       type: 'game', category: 'racing',   icon: '🏎️' },
  'assettocorsacompetizione.exe':      { name: 'ACC',                 type: 'game', category: 'racing',   icon: '🏎️' },
  'beamng.drive.exe':                  { name: 'BeamNG.drive',        type: 'game', category: 'racing',   icon: '🏎️' },
  'iracingservice.exe':                { name: 'iRacing',             type: 'game', category: 'racing',   icon: '🏎️' },
  'rf2.exe':                           { name: 'rFactor 2',           type: 'game', category: 'racing',   icon: '🏎️' },
  'rocketleague.exe':                  { name: 'Rocket League',       type: 'game', category: 'sports',   icon: '🚗' },
  'madden24.exe':                      { name: 'Madden 24',           type: 'game', category: 'sports',   icon: '🏈' },
  'pga2k23.exe':                       { name: 'PGA Tour 2K23',       type: 'game', category: 'sports',   icon: '⛳' },

  // ─── HORROR / SURVIVAL ──────────────────────────────────────────────────────
  'deadbydaylight.exe':                { name: 'Dead by Daylight',    type: 'game', category: 'horror',   icon: '😱' },
  'phasmophobia.exe':                  { name: 'Phasmophobia',        type: 'game', category: 'horror',   icon: '👻' },
  'residentevilvillage.exe':           { name: 'Resident Evil Village',type: 'game',category: 'horror',   icon: '😱' },
  'residentevil4.exe':                 { name: 'Resident Evil 4',     type: 'game', category: 'horror',   icon: '😱' },
  'outlast.exe':                       { name: 'Outlast',             type: 'game', category: 'horror',   icon: '😱' },
  'visage.exe':                        { name: 'Visage',              type: 'game', category: 'horror',   icon: '😱' },
  'silenthill.exe':                    { name: 'Silent Hill 2',       type: 'game', category: 'horror',   icon: '😱' },
  'lethal company.exe':                { name: 'Lethal Company',      type: 'game', category: 'horror',   icon: '👻' },
  'content warning.exe':               { name: 'Content Warning',     type: 'game', category: 'horror',   icon: '👻' },

  // ─── INDIE / PUZZLE ─────────────────────────────────────────────────────────
  'hades.exe':                         { name: 'Hades',               type: 'game', category: 'indie',    icon: '🎮' },
  'hades2.exe':                        { name: 'Hades II',            type: 'game', category: 'indie',    icon: '🎮' },
  'hollowknight.exe':                  { name: 'Hollow Knight',       type: 'game', category: 'indie',    icon: '🎮' },
  'silksong.exe':                      { name: 'Silksong',            type: 'game', category: 'indie',    icon: '🎮' },
  'celeste.exe':                       { name: 'Celeste',             type: 'game', category: 'indie',    icon: '🎮' },
  'deadcells.exe':                     { name: 'Dead Cells',          type: 'game', category: 'indie',    icon: '🎮' },
  'cuphead.exe':                       { name: 'Cuphead',             type: 'game', category: 'indie',    icon: '🎮' },
  'undertale.exe':                     { name: 'Undertale',           type: 'game', category: 'indie',    icon: '🎮' },
  'deltarune.exe':                     { name: 'Deltarune',           type: 'game', category: 'indie',    icon: '🎮' },
  'katana zero.exe':                   { name: 'Katana ZERO',         type: 'game', category: 'indie',    icon: '🎮' },
  'disco elysium.exe':                 { name: 'Disco Elysium',       type: 'game', category: 'indie',    icon: '🎮' },
  'untitled goose game.exe':           { name: 'Untitled Goose Game', type: 'game', category: 'indie',    icon: '🪿' },
  'among us.exe':                      { name: 'Among Us',            type: 'game', category: 'indie',    icon: '🎮' },
  'vampire survivors.exe':             { name: 'Vampire Survivors',   type: 'game', category: 'indie',    icon: '🧛' },
  'brotato.exe':                       { name: 'Brotato',             type: 'game', category: 'indie',    icon: '🥔' },
  'balatro.exe':                       { name: 'Balatro',             type: 'game', category: 'indie',    icon: '🃏' },
  'buckshot roulette.exe':             { name: 'Buckshot Roulette',   type: 'game', category: 'indie',    icon: '🎮' },
  'neon white.exe':                    { name: 'Neon White',          type: 'game', category: 'indie',    icon: '🎮' },
  'tunic.exe':                         { name: 'Tunic',               type: 'game', category: 'indie',    icon: '🎮' },
  'dredge.exe':                        { name: 'Dredge',              type: 'game', category: 'indie',    icon: '🎮' },
  'pasta.exe':                         { name: 'Pasta',               type: 'game', category: 'indie',    icon: '🎮' },
  'spiritfarer.exe':                   { name: 'Spiritfarer',         type: 'game', category: 'indie',    icon: '🎮' },
  'ori.exe':                           { name: 'Ori',                 type: 'game', category: 'indie',    icon: '🎮' },
  'firewatch.exe':                     { name: 'Firewatch',           type: 'game', category: 'indie',    icon: '🎮' },
  'undertale64.exe':                   { name: 'Undertale',           type: 'game', category: 'indie',    icon: '🎮' },
  'dave the diver.exe':                { name: 'Dave the Diver',      type: 'game', category: 'indie',    icon: '🤿' },
  'sea of stars.exe':                  { name: 'Sea of Stars',        type: 'game', category: 'indie',    icon: '⭐' },
  'pizza tower.exe':                   { name: 'Pizza Tower',         type: 'game', category: 'indie',    icon: '🍕' },
  'core keeper.exe':                   { name: 'Core Keeper',         type: 'game', category: 'indie',    icon: '🎮' },

  // ─── SIMULATION ─────────────────────────────────────────────────────────────
  'fsx.exe':                           { name: 'Flight Simulator X',  type: 'game', category: 'sim',      icon: '✈️' },
  'msfs.exe':                          { name: 'Microsoft Flight Simulator', type: 'game', category: 'sim', icon: '✈️' },
  'flightsimulatorclient.exe':         { name: 'Flight Simulator 2024', type: 'game', category: 'sim',    icon: '✈️' },
  'prepar3d.exe':                      { name: 'Prepar3D',            type: 'game', category: 'sim',      icon: '✈️' },
  'xplane.exe':                        { name: 'X-Plane 12',          type: 'game', category: 'sim',      icon: '✈️' },
  'euro truck simulator 2.exe':        { name: 'Euro Truck Simulator 2', type: 'game', category: 'sim',   icon: '🚛' },
  'american truck simulator.exe':      { name: 'American Truck Simulator', type: 'game', category: 'sim', icon: '🚛' },
  'spaceengineers.exe':                { name: 'Space Engineers',     type: 'game', category: 'sim',      icon: '🚀' },
  'planetcoaster.exe':                 { name: 'Planet Coaster',      type: 'game', category: 'sim',      icon: '🎢' },
  'planetcoaster2.exe':                { name: 'Planet Coaster 2',    type: 'game', category: 'sim',      icon: '🎢' },
  'planetzoo.exe':                     { name: 'Planet Zoo',          type: 'game', category: 'sim',      icon: '🦁' },
  'twopointcampus.exe':                { name: 'Two Point Campus',    type: 'game', category: 'sim',      icon: '🎓' },
  'twopointhospital.exe':              { name: 'Two Point Hospital',  type: 'game', category: 'sim',      icon: '🏥' },
  'thesims4.exe':                      { name: 'The Sims 4',          type: 'game', category: 'sim',      icon: '🏠' },
  'stormworks.exe':                    { name: 'Stormworks',          type: 'game', category: 'sim',      icon: '🚁' },
  'kerbalspaceprogram.exe':            { name: 'Kerbal Space Program', type: 'game', category: 'sim',     icon: '🚀' },
  'ksp2.exe':                          { name: 'KSP 2',               type: 'game', category: 'sim',      icon: '🚀' },
  'farmingsimulator22.exe':            { name: 'Farming Simulator 22',type: 'game', category: 'sim',      icon: '🚜' },
  'farmingsimulator25.exe':            { name: 'Farming Simulator 25',type: 'game', category: 'sim',      icon: '🚜' },
  'powerwash simulator.exe':           { name: 'PowerWash Simulator', type: 'game', category: 'sim',      icon: '🚿' },
  'chained echoes.exe':                { name: 'Chained Echoes',      type: 'game', category: 'sim',      icon: '🎮' },

  // ─── FIGHTING GAMES ─────────────────────────────────────────────────────────
  'streetfighter6.exe':                { name: 'Street Fighter 6',    type: 'game', category: 'fighting', icon: '👊' },
  'mortalkombatonegame.exe':           { name: 'Mortal Kombat 1',     type: 'game', category: 'fighting', icon: '👊' },
  'tekken8.exe':                       { name: 'Tekken 8',            type: 'game', category: 'fighting', icon: '👊' },
  'guiltygear.exe':                    { name: 'Guilty Gear Strive',  type: 'game', category: 'fighting', icon: '👊' },
  'granblue.exe':                      { name: 'Granblue Fantasy Versus', type: 'game', category: 'fighting', icon: '👊' },
  'multiversus.exe':                   { name: 'MultiVersus',         type: 'game', category: 'fighting', icon: '👊' },
  'dragonballsparking.exe':            { name: 'Dragon Ball: Sparking Zero', type: 'game', category: 'fighting', icon: '🐉' },
  'ninjastorm4.exe':                   { name: 'Naruto Ninja Storm 4',type: 'game', category: 'fighting', icon: '🥷' },

  // ─── GAME LAUNCHERS ─────────────────────────────────────────────────────────
  'steam.exe':                         { name: 'Steam',               type: 'launcher', category: 'launcher',  icon: '🎮' },
  'epicgameslauncher.exe':             { name: 'Epic Games Launcher', type: 'launcher', category: 'launcher',  icon: '🎮' },
  'riotclientservices.exe':            { name: 'Riot Client',         type: 'launcher', category: 'launcher',  icon: '🎮' },
  'battlenet.exe':                     { name: 'Battle.net',          type: 'launcher', category: 'launcher',  icon: '🎮' },
  'gog galaxy.exe':                    { name: 'GOG Galaxy',          type: 'launcher', category: 'launcher',  icon: '🎮' },
  'goggalaxy.exe':                     { name: 'GOG Galaxy',          type: 'launcher', category: 'launcher',  icon: '🎮' },
  'ubisoftconnect.exe':                { name: 'Ubisoft Connect',     type: 'launcher', category: 'launcher',  icon: '🎮' },
  'upc.exe':                           { name: 'Ubisoft Connect',     type: 'launcher', category: 'launcher',  icon: '🎮' },
  'origin.exe':                        { name: 'EA App',              type: 'launcher', category: 'launcher',  icon: '🎮' },
  'easfc.exe':                         { name: 'EA App',              type: 'launcher', category: 'launcher',  icon: '🎮' },
  'eadesktop.exe':                     { name: 'EA App',              type: 'launcher', category: 'launcher',  icon: '🎮' },
  'rockstarlaunch.exe':                { name: 'Rockstar Launcher',   type: 'launcher', category: 'launcher',  icon: '🎮' },
  'bethesdanet.exe':                   { name: 'Bethesda.net',        type: 'launcher', category: 'launcher',  icon: '🎮' },
  'playnite.desktop.exe':              { name: 'Playnite',            type: 'launcher', category: 'launcher',  icon: '🎮' },
  'heroiclauncher.exe':                { name: 'Heroic Launcher',     type: 'launcher', category: 'launcher',  icon: '🎮' },
  'itchio.exe':                        { name: 'itch.io',             type: 'launcher', category: 'launcher',  icon: '🎮' },
  'modhub.exe':                        { name: 'ModHub',              type: 'launcher', category: 'launcher',  icon: '🎮' },
  'parsec.exe':                        { name: 'Parsec',              type: 'app',      category: 'gaming',    icon: '🎮' },
  'moonlightportable.exe':             { name: 'Moonlight',           type: 'app',      category: 'gaming',    icon: '🎮' },
  'nvidia share.exe':                  { name: 'NVIDIA ShadowPlay',   type: 'app',      category: 'gaming',    icon: '🎮' },
  'nvcontainer.exe':                   { name: 'NVIDIA Container',    type: 'app',      category: 'gaming',    icon: '🎮' },

  // ─── MUSIC APPS ─────────────────────────────────────────────────────────────
  'spotify.exe':                       { name: 'Spotify',             type: 'music', category: 'music',        icon: '🎵' },
  'tidal.exe':                         { name: 'TIDAL',               type: 'music', category: 'music',        icon: '🎵' },
  'applemusic.exe':                    { name: 'Apple Music',         type: 'music', category: 'music',        icon: '🎵' },
  'itunes.exe':                        { name: 'iTunes',              type: 'music', category: 'music',        icon: '🎵' },
  'deezer.exe':                        { name: 'Deezer',              type: 'music', category: 'music',        icon: '🎵' },
  'soundcloud.exe':                    { name: 'SoundCloud',          type: 'music', category: 'music',        icon: '🎵' },
  'amazonmusic.exe':                   { name: 'Amazon Music',        type: 'music', category: 'music',        icon: '🎵' },
  'musicbee.exe':                      { name: 'MusicBee',            type: 'music', category: 'music',        icon: '🎵' },
  'foobar2000.exe':                    { name: 'foobar2000',          type: 'music', category: 'music',        icon: '🎵' },
  'vlc.exe':                           { name: 'VLC',                 type: 'media', category: 'media',        icon: '🎬' },
  'winamp.exe':                        { name: 'Winamp',              type: 'music', category: 'music',        icon: '🎵' },
  'aimp.exe':                          { name: 'AIMP',                type: 'music', category: 'music',        icon: '🎵' },
  'dopamine.exe':                      { name: 'Dopamine',            type: 'music', category: 'music',        icon: '🎵' },
  'strawberry.exe':                    { name: 'Strawberry',          type: 'music', category: 'music',        icon: '🍓' },
  'clementine.exe':                    { name: 'Clementine',          type: 'music', category: 'music',        icon: '🎵' },

  // ─── BROWSERS ───────────────────────────────────────────────────────────────
  'chrome.exe':                        { name: 'Google Chrome',       type: 'browser', category: 'browser',    icon: '🌐' },
  'msedge.exe':                        { name: 'Microsoft Edge',      type: 'browser', category: 'browser',    icon: '🌐' },
  'firefox.exe':                       { name: 'Firefox',             type: 'browser', category: 'browser',    icon: '🌐' },
  'opera.exe':                         { name: 'Opera',               type: 'browser', category: 'browser',    icon: '🌐' },
  'operagx.exe':                       { name: 'Opera GX',            type: 'browser', category: 'browser',    icon: '🌐' },
  'brave.exe':                         { name: 'Brave',               type: 'browser', category: 'browser',    icon: '🦁' },
  'vivaldi.exe':                       { name: 'Vivaldi',             type: 'browser', category: 'browser',    icon: '🌐' },
  'waterfox.exe':                      { name: 'Waterfox',            type: 'browser', category: 'browser',    icon: '🌐' },
  'librewolf.exe':                     { name: 'LibreWolf',           type: 'browser', category: 'browser',    icon: '🌐' },
  'thorium.exe':                       { name: 'Thorium',             type: 'browser', category: 'browser',    icon: '🌐' },
  'arc.exe':                           { name: 'Arc Browser',         type: 'browser', category: 'browser',    icon: '🌐' },
  'floorp.exe':                        { name: 'Floorp',              type: 'browser', category: 'browser',    icon: '🌐' },
  'tor browser.exe':                   { name: 'Tor Browser',         type: 'browser', category: 'browser',    icon: '🧅' },

  // ─── DEVELOPER TOOLS ────────────────────────────────────────────────────────
  'code.exe':                          { name: 'VS Code',             type: 'dev', category: 'editor',         icon: '💻' },
  'cursor.exe':                        { name: 'Cursor',              type: 'dev', category: 'editor',         icon: '💻' },
  'windsurf.exe':                      { name: 'Windsurf',            type: 'dev', category: 'editor',         icon: '💻' },
  'devenv.exe':                        { name: 'Visual Studio',       type: 'dev', category: 'editor',         icon: '💻' },
  'idea64.exe':                        { name: 'IntelliJ IDEA',       type: 'dev', category: 'editor',         icon: '💻' },
  'webstorm64.exe':                    { name: 'WebStorm',            type: 'dev', category: 'editor',         icon: '💻' },
  'phpstorm64.exe':                    { name: 'PhpStorm',            type: 'dev', category: 'editor',         icon: '💻' },
  'pycharm64.exe':                     { name: 'PyCharm',             type: 'dev', category: 'editor',         icon: '🐍' },
  'datagrip64.exe':                    { name: 'DataGrip',            type: 'dev', category: 'editor',         icon: '💻' },
  'clion64.exe':                       { name: 'CLion',               type: 'dev', category: 'editor',         icon: '💻' },
  'rider64.exe':                       { name: 'Rider',               type: 'dev', category: 'editor',         icon: '💻' },
  'goland64.exe':                      { name: 'GoLand',              type: 'dev', category: 'editor',         icon: '💻' },
  'rubymine64.exe':                    { name: 'RubyMine',            type: 'dev', category: 'editor',         icon: '💎' },
  'fleet.exe':                         { name: 'Fleet',               type: 'dev', category: 'editor',         icon: '💻' },
  'sublime_text.exe':                  { name: 'Sublime Text',        type: 'dev', category: 'editor',         icon: '💻' },
  'atom.exe':                          { name: 'Atom',                type: 'dev', category: 'editor',         icon: '💻' },
  'notepad++.exe':                     { name: 'Notepad++',           type: 'dev', category: 'editor',         icon: '💻' },
  'zed.exe':                           { name: 'Zed',                 type: 'dev', category: 'editor',         icon: '⚡' },
  'helix.exe':                         { name: 'Helix',               type: 'dev', category: 'editor',         icon: '💻' },
  'neovide.exe':                       { name: 'Neovide',             type: 'dev', category: 'editor',         icon: '💻' },
  'emacs.exe':                         { name: 'Emacs',               type: 'dev', category: 'editor',         icon: '💻' },
  'cmd.exe':                           { name: 'Command Prompt',      type: 'dev', category: 'terminal',       icon: '⌨️' },
  'powershell.exe':                    { name: 'PowerShell',          type: 'dev', category: 'terminal',       icon: '⌨️' },
  'windowsterminal.exe':               { name: 'Windows Terminal',    type: 'dev', category: 'terminal',       icon: '⌨️' },
  'wt.exe':                            { name: 'Windows Terminal',    type: 'dev', category: 'terminal',       icon: '⌨️' },
  'wezterm-gui.exe':                   { name: 'WezTerm',             type: 'dev', category: 'terminal',       icon: '⌨️' },
  'alacritty.exe':                     { name: 'Alacritty',           type: 'dev', category: 'terminal',       icon: '⌨️' },
  'mintty.exe':                        { name: 'Cygwin/MSYS2',        type: 'dev', category: 'terminal',       icon: '⌨️' },
  'gitkraken.exe':                     { name: 'GitKraken',           type: 'dev', category: 'git',            icon: '🐙' },
  'sourcetree.exe':                    { name: 'Sourcetree',          type: 'dev', category: 'git',            icon: '🌳' },
  'github desktop.exe':                { name: 'GitHub Desktop',      type: 'dev', category: 'git',            icon: '🐙' },
  'fork.exe':                          { name: 'Fork (Git)',          type: 'dev', category: 'git',            icon: '🍴' },
  'tableplus.exe':                     { name: 'TablePlus',           type: 'dev', category: 'database',       icon: '🗄️' },
  'dbeaver.exe':                       { name: 'DBeaver',             type: 'dev', category: 'database',       icon: '🗄️' },
  'heidisql.exe':                      { name: 'HeidiSQL',            type: 'dev', category: 'database',       icon: '🗄️' },
  'postman.exe':                       { name: 'Postman',             type: 'dev', category: 'api',            icon: '📮' },
  'insomnia.exe':                      { name: 'Insomnia',            type: 'dev', category: 'api',            icon: '📮' },
  'docker desktop.exe':                { name: 'Docker Desktop',      type: 'dev', category: 'devops',         icon: '🐳' },
  'dockerdesktop.exe':                 { name: 'Docker Desktop',      type: 'dev', category: 'devops',         icon: '🐳' },
  'virtualbox.exe':                    { name: 'VirtualBox',          type: 'dev', category: 'vm',             icon: '💾' },
  'vmplayer.exe':                      { name: 'VMware Player',       type: 'dev', category: 'vm',             icon: '💾' },
  'vmware.exe':                        { name: 'VMware Workstation',  type: 'dev', category: 'vm',             icon: '💾' },
  'wireshark.exe':                     { name: 'Wireshark',           type: 'dev', category: 'network',        icon: '🔬' },
  'burpsuite.exe':                     { name: 'Burp Suite',          type: 'dev', category: 'security',       icon: '🔐' },
  'figma.exe':                         { name: 'Figma',               type: 'dev', category: 'design',         icon: '🎨' },

  // ─── CREATIVE / DESIGN ──────────────────────────────────────────────────────
  'photoshop.exe':                     { name: 'Photoshop',           type: 'creative', category: 'design',    icon: '🎨' },
  'illustrator.exe':                   { name: 'Illustrator',         type: 'creative', category: 'design',    icon: '🎨' },
  'premiere.exe':                      { name: 'Premiere Pro',        type: 'creative', category: 'video',     icon: '🎬' },
  'premierepro.exe':                   { name: 'Premiere Pro',        type: 'creative', category: 'video',     icon: '🎬' },
  'afterfx.exe':                       { name: 'After Effects',       type: 'creative', category: 'video',     icon: '✨' },
  'indesign.exe':                      { name: 'InDesign',            type: 'creative', category: 'design',    icon: '📰' },
  'xd.exe':                            { name: 'Adobe XD',            type: 'creative', category: 'design',    icon: '🎨' },
  'acrobat.exe':                       { name: 'Adobe Acrobat',       type: 'productivity', category: 'document', icon: '📄' },
  'mediaencoder.exe':                  { name: 'Media Encoder',       type: 'creative', category: 'video',     icon: '🎬' },
  'audition.exe':                      { name: 'Adobe Audition',      type: 'creative', category: 'audio',     icon: '🎙️' },
  'blender.exe':                       { name: 'Blender',             type: 'creative', category: '3d',        icon: '🟠' },
  'cinema 4d.exe':                     { name: 'Cinema 4D',           type: 'creative', category: '3d',        icon: '🎬' },
  'maya.exe':                          { name: 'Maya',                type: 'creative', category: '3d',        icon: '🎬' },
  '3dsmax.exe':                        { name: '3ds Max',             type: 'creative', category: '3d',        icon: '🎬' },
  'zbrush.exe':                        { name: 'ZBrush',              type: 'creative', category: '3d',        icon: '🖌️' },
  'substance painter.exe':             { name: 'Substance Painter',   type: 'creative', category: '3d',        icon: '🎨' },
  'houdini.exe':                       { name: 'Houdini',             type: 'creative', category: '3d',        icon: '🎬' },
  'davinciresolve.exe':                { name: 'DaVinci Resolve',     type: 'creative', category: 'video',     icon: '🎬' },
  'resolve.exe':                       { name: 'DaVinci Resolve',     type: 'creative', category: 'video',     icon: '🎬' },
  'capcut.exe':                        { name: 'CapCut',              type: 'creative', category: 'video',     icon: '🎬' },
  'clipchamp.exe':                     { name: 'Clipchamp',           type: 'creative', category: 'video',     icon: '🎬' },
  'vegas pro.exe':                     { name: 'Vegas Pro',           type: 'creative', category: 'video',     icon: '🎬' },
  'final cut pro.exe':                 { name: 'Final Cut Pro',       type: 'creative', category: 'video',     icon: '🎬' },
  'krita.exe':                         { name: 'Krita',               type: 'creative', category: 'design',    icon: '🎨' },
  'inkscape.exe':                      { name: 'Inkscape',            type: 'creative', category: 'design',    icon: '🎨' },
  'gimp-2.10.exe':                     { name: 'GIMP',                type: 'creative', category: 'design',    icon: '🎨' },
  'gimp.exe':                          { name: 'GIMP',                type: 'creative', category: 'design',    icon: '🎨' },
  'affinity photo.exe':                { name: 'Affinity Photo',      type: 'creative', category: 'design',    icon: '🎨' },
  'affinity designer.exe':             { name: 'Affinity Designer',   type: 'creative', category: 'design',    icon: '🎨' },
  'canva.exe':                         { name: 'Canva',               type: 'creative', category: 'design',    icon: '🎨' },
  'fl studio.exe':                     { name: 'FL Studio',           type: 'creative', category: 'audio',     icon: '🎹' },
  'ableton live.exe':                  { name: 'Ableton Live',        type: 'creative', category: 'audio',     icon: '🎹' },
  'ableton.exe':                       { name: 'Ableton Live',        type: 'creative', category: 'audio',     icon: '🎹' },
  'cubase12.exe':                      { name: 'Cubase',              type: 'creative', category: 'audio',     icon: '🎹' },
  'logic pro x.exe':                   { name: 'Logic Pro X',         type: 'creative', category: 'audio',     icon: '🎹' },
  'reaper.exe':                        { name: 'REAPER',              type: 'creative', category: 'audio',     icon: '🎙️' },
  'studio one.exe':                    { name: 'Studio One',          type: 'creative', category: 'audio',     icon: '🎵' },
  'audacity.exe':                      { name: 'Audacity',            type: 'creative', category: 'audio',     icon: '🎙️' },
  'obs64.exe':                         { name: 'OBS Studio',          type: 'media',    category: 'streaming', icon: '📹' },
  'obs32.exe':                         { name: 'OBS Studio',          type: 'media',    category: 'streaming', icon: '📹' },
  'streamlabs obs.exe':                { name: 'Streamlabs',          type: 'media',    category: 'streaming', icon: '📹' },
  'streamlabs.exe':                    { name: 'Streamlabs',          type: 'media',    category: 'streaming', icon: '📹' },
  'xsplit.core.exe':                   { name: 'XSplit',              type: 'media',    category: 'streaming', icon: '📹' },
  'twitch.exe':                        { name: 'Twitch',              type: 'media',    category: 'streaming', icon: '💜' },
  'castify.exe':                       { name: 'Screencastify',       type: 'media',    category: 'streaming', icon: '📹' },
  'lightstream studio.exe':            { name: 'Lightstream',         type: 'media',    category: 'streaming', icon: '📹' },
  'unity.exe':                         { name: 'Unity',               type: 'dev',      category: 'gamedev',   icon: '🕹️' },
  'unityhub.exe':                      { name: 'Unity Hub',           type: 'dev',      category: 'gamedev',   icon: '🕹️' },
  'ue5editor-win64-debug.exe':         { name: 'Unreal Engine 5',     type: 'dev',      category: 'gamedev',   icon: '🕹️' },
  'unrealengine.exe':                  { name: 'Unreal Engine',       type: 'dev',      category: 'gamedev',   icon: '🕹️' },
  'godot.exe':                         { name: 'Godot Engine',        type: 'dev',      category: 'gamedev',   icon: '🕹️' },
  'gamemaker.exe':                     { name: 'GameMaker',           type: 'dev',      category: 'gamedev',   icon: '🕹️' },

  // ─── COMMUNICATION ──────────────────────────────────────────────────────────
  'discord.exe':                       { name: 'Discord',             type: 'communication', category: 'chat', icon: '💬' },
  'teams.exe':                         { name: 'Microsoft Teams',     type: 'communication', category: 'chat', icon: '💬' },
  'slack.exe':                         { name: 'Slack',               type: 'communication', category: 'chat', icon: '💬' },
  'zoom.exe':                          { name: 'Zoom',                type: 'communication', category: 'video-call', icon: '📹' },
  'skype.exe':                         { name: 'Skype',               type: 'communication', category: 'video-call', icon: '📞' },
  'telegram.exe':                      { name: 'Telegram',            type: 'communication', category: 'chat', icon: '✈️' },
  'whatsapp.exe':                      { name: 'WhatsApp',            type: 'communication', category: 'chat', icon: '💬' },
  'signal.exe':                        { name: 'Signal',              type: 'communication', category: 'chat', icon: '🔐' },
  'viber.exe':                         { name: 'Viber',               type: 'communication', category: 'chat', icon: '📞' },
  'element.exe':                       { name: 'Element',             type: 'communication', category: 'chat', icon: '💬' },
  'guilded.exe':                       { name: 'Guilded',             type: 'communication', category: 'chat', icon: '🟡' },
  'revolt.exe':                        { name: 'Revolt',              type: 'communication', category: 'chat', icon: '💬' },

  // ─── PRODUCTIVITY ───────────────────────────────────────────────────────────
  'winword.exe':                       { name: 'Microsoft Word',      type: 'productivity', category: 'office', icon: '📝' },
  'excel.exe':                         { name: 'Microsoft Excel',     type: 'productivity', category: 'office', icon: '📊' },
  'powerpnt.exe':                      { name: 'PowerPoint',          type: 'productivity', category: 'office', icon: '📊' },
  'onenote.exe':                       { name: 'OneNote',             type: 'productivity', category: 'office', icon: '📓' },
  'outlook.exe':                       { name: 'Outlook',             type: 'productivity', category: 'email',  icon: '📧' },
  'notion.exe':                        { name: 'Notion',              type: 'productivity', category: 'notes',  icon: '📝' },
  'obsidian.exe':                      { name: 'Obsidian',            type: 'productivity', category: 'notes',  icon: '💎' },
  'logseq.exe':                        { name: 'Logseq',              type: 'productivity', category: 'notes',  icon: '📝' },
  'roamresearch.exe':                  { name: 'Roam Research',       type: 'productivity', category: 'notes',  icon: '📝' },
  'anki.exe':                          { name: 'Anki',                type: 'productivity', category: 'study',  icon: '🎓' },
  'todoist.exe':                       { name: 'Todoist',             type: 'productivity', category: 'tasks',  icon: '✅' },
  'ticktick.exe':                      { name: 'TickTick',            type: 'productivity', category: 'tasks',  icon: '✅' },
  'anydo.exe':                         { name: 'Any.do',              type: 'productivity', category: 'tasks',  icon: '✅' },
  'thunderbird.exe':                   { name: 'Thunderbird',         type: 'productivity', category: 'email',  icon: '📧' },
  'bitwarden.exe':                     { name: 'Bitwarden',           type: 'productivity', category: 'security', icon: '🔐' },
  '1password.exe':                     { name: '1Password',           type: 'productivity', category: 'security', icon: '🔑' },
  'keepass.exe':                       { name: 'KeePass',             type: 'productivity', category: 'security', icon: '🔐' },
  'libreoffice writer.exe':            { name: 'LibreOffice Writer',  type: 'productivity', category: 'office',   icon: '📝' },
  'soffice.exe':                       { name: 'LibreOffice',         type: 'productivity', category: 'office',   icon: '📄' },
  'wpsoffice.exe':                     { name: 'WPS Office',          type: 'productivity', category: 'office',   icon: '📄' },
  'adobe reader.exe':                  { name: 'Adobe Reader',        type: 'productivity', category: 'document', icon: '📄' },
  'foxit reader.exe':                  { name: 'Foxit Reader',        type: 'productivity', category: 'document', icon: '📄' },
  'notepad.exe':                       { name: 'Notepad',             type: 'productivity', category: 'notes',    icon: '📝' },
  'calculator.exe':                    { name: 'Calculator',          type: 'productivity', category: 'tool',     icon: '🧮' },
  'mspaint.exe':                       { name: 'MS Paint',            type: 'productivity', category: 'tool',     icon: '🖌️' },
  'paint.exe':                         { name: 'Paint',               type: 'productivity', category: 'tool',     icon: '🖌️' },

  // ─── MEDIA PLAYERS ──────────────────────────────────────────────────────────
  'mpv.exe':                           { name: 'mpv',                 type: 'media', category: 'player',  icon: '🎬' },
  'mpc-hc.exe':                        { name: 'MPC-HC',              type: 'media', category: 'player',  icon: '🎬' },
  'mpc-hc64.exe':                      { name: 'MPC-HC',              type: 'media', category: 'player',  icon: '🎬' },
  'mpc-be.exe':                        { name: 'MPC-BE',              type: 'media', category: 'player',  icon: '🎬' },
  'kmplayer.exe':                      { name: 'KMPlayer',            type: 'media', category: 'player',  icon: '🎬' },
  'potplayer.exe':                     { name: 'PotPlayer',           type: 'media', category: 'player',  icon: '🎬' },
  'potplayermini64.exe':               { name: 'PotPlayer',           type: 'media', category: 'player',  icon: '🎬' },
  'netflix.exe':                       { name: 'Netflix',             type: 'media', category: 'streaming', icon: '🎬' },
  'disneyplus.exe':                    { name: 'Disney+',             type: 'media', category: 'streaming', icon: '🎬' },
  'primevideo.exe':                    { name: 'Prime Video',         type: 'media', category: 'streaming', icon: '🎬' },
  'hbomax.exe':                        { name: 'HBO Max',             type: 'media', category: 'streaming', icon: '🎬' },
  'peacock.exe':                       { name: 'Peacock',             type: 'media', category: 'streaming', icon: '🎬' },
  'hulu.exe':                          { name: 'Hulu',                type: 'media', category: 'streaming', icon: '🎬' },
  'plex.exe':                          { name: 'Plex',                type: 'media', category: 'streaming', icon: '🎬' },
  'jellyfin.exe':                      { name: 'Jellyfin',            type: 'media', category: 'streaming', icon: '🎬' },
  'kodi.exe':                          { name: 'Kodi',                type: 'media', category: 'streaming', icon: '🎬' },
  'emby.exe':                          { name: 'Emby',                type: 'media', category: 'streaming', icon: '🎬' },
  'crunchyroll.exe':                   { name: 'Crunchyroll',         type: 'media', category: 'streaming', icon: '🍡' },

  // ─── ANIME / READING ────────────────────────────────────────────────────────
  'calibre.exe':                       { name: 'Calibre (E-books)',   type: 'productivity', category: 'reading', icon: '📚' },
  'kindle.exe':                        { name: 'Kindle',              type: 'media', category: 'reading',        icon: '📚' },
  'sumatra pdf.exe':                   { name: 'SumatraPDF',          type: 'productivity', category: 'document', icon: '📄' },
  'kotatsu.exe':                       { name: 'Kotatsu',             type: 'media', category: 'reading',        icon: '📖' },

  // ─── SYSTEM / UTILITY (show-worthy) ─────────────────────────────────────────
  'taskmgr.exe':                       { name: 'Task Manager',        type: 'app', category: 'system',    icon: '⚙️' },
  'msiafterburner.exe':                { name: 'MSI Afterburner',     type: 'app', category: 'system',    icon: '🔥' },
  'hwinfo64.exe':                      { name: 'HWiNFO64',            type: 'app', category: 'system',    icon: '📊' },
  'cpu-z.exe':                         { name: 'CPU-Z',               type: 'app', category: 'system',    icon: '🔬' },
  'gpu-z.exe':                         { name: 'GPU-Z',               type: 'app', category: 'system',    icon: '🔬' },
  'speccy.exe':                        { name: 'Speccy',              type: 'app', category: 'system',    icon: '📊' },
  'malwarebytes.exe':                  { name: 'Malwarebytes',        type: 'app', category: 'security',  icon: '🛡️' },
  'windowsdefender.exe':               { name: 'Windows Defender',    type: 'app', category: 'security',  icon: '🛡️' },
  'everything.exe':                    { name: 'Everything (Search)', type: 'app', category: 'utility',   icon: '🔍' },
  'sharex.exe':                        { name: 'ShareX',              type: 'app', category: 'utility',   icon: '📸' },
  'greenshot.exe':                     { name: 'Greenshot',           type: 'app', category: 'utility',   icon: '📸' },
  'flameshot.exe':                     { name: 'Flameshot',           type: 'app', category: 'utility',   icon: '📸' },
  '7zfm.exe':                          { name: '7-Zip',               type: 'app', category: 'utility',   icon: '📦' },
  'winrar.exe':                        { name: 'WinRAR',              type: 'app', category: 'utility',   icon: '📦' },
  'nanazip.exe':                       { name: 'NanaZip',             type: 'app', category: 'utility',   icon: '📦' },
  'explorerpatcher.exe':               { name: 'ExplorerPatcher',     type: 'app', category: 'utility',   icon: '⚙️' },
  'rainmeter.exe':                     { name: 'Rainmeter',           type: 'app', category: 'utility',   icon: '🌧️' },
  'powertoys.exe':                     { name: 'PowerToys',           type: 'app', category: 'utility',   icon: '🔧' },
  'autohotkey.exe':                    { name: 'AutoHotkey',          type: 'dev', category: 'utility',   icon: '⌨️' },
  'fluentterminal.exe':                { name: 'Fluent Terminal',     type: 'dev', category: 'terminal',  icon: '⌨️' },
  'hyper.exe':                         { name: 'Hyper Terminal',      type: 'dev', category: 'terminal',  icon: '⌨️' },
};

/** Type priority for when multiple processes are detected simultaneously. */
export const TYPE_PRIORITY = ['game', 'music', 'creative', 'dev', 'communication', 'media', 'browser', 'launcher', 'productivity', 'app'];

/**
 * Processes that should always be ignored regardless of name matching.
 * These are OS internals, system daemons, and background noise.
 */
export const PROCESS_BLOCKLIST = new Set([
  'svchost.exe', 'runtimebroker.exe', 'system', 'registry', 'smss.exe',
  'csrss.exe', 'wininit.exe', 'winlogon.exe', 'services.exe', 'lsass.exe',
  'dwm.exe', 'explorer.exe', 'taskhostw.exe', 'sihost.exe', 'fontdrvhost.exe',
  'searchhost.exe', 'searchindexer.exe', 'searchapp.exe', 'ctfmon.exe',
  'audiodg.exe', 'wuauclt.exe', 'msiexec.exe', 'spoolsv.exe', 'taskmgr.exe',
  'dllhost.exe', 'conhost.exe', 'backgroundtaskhost.exe', 'compattelrunner.exe',
  'securityhealthservice.exe', 'securityhealthsystray.exe', 'msmpeng.exe',
  'nissrv.exe', 'antimalware service executable', 'wmirvse.exe', 'wmiprvse.exe',
  'igfxcuiservice.exe', 'igfxem.exe', 'igfxhk.exe', 'amdow.exe',
  'nvdisplay.container.exe', 'nvcontainer.exe', 'nvcplui.exe',
  'amdrsserv.exe', 'cncmd.exe', 'radeoninstaller.exe',
  'textinputhost.exe', 'sppsvc.exe', 'sppextcomobj.exe',
  'usocoreworker.exe', 'musnotification.exe', 'startmenuexperiencehost.exe',
  'shellexperiencehost.exe', 'applicationframehost.exe', 'systemsettings.exe',
  'lockapp.exe', 'logonui.exe', 'crashdump64.exe', 'werfault.exe',
  'wermgr.exe', 'sppextcomobj.exe', 'ngen.exe', 'ngentask.exe',
  'microsoftedgeupdate.exe', 'googleupdate.exe', 'acrocrdsvc.exe',
  'acrord32.exe', 'adobearm.exe', 'ccxprocess.exe', 'armsvc.exe',
  'adobecollabsync.exe', 'crashreporter.exe', 'updater.exe',
  'setup.exe', 'unins000.exe', 'uninstall.exe', 'installer.exe',
]);
